INSERT INTO UserTab (UserID, EMail, Name, LastName) VALUES	

							(0, 'leer0@mail.de', 'Leerman', 'von Leer');

INSERT INTO UserTab (EMail, Name, LastName) VALUES	

							('SuperUser@mail.de','Super','User'),
							('Admin1@shop.de','Eins','Admin'),
							('Admin2@shop.de','Zwei','Admin'),
							('SuppPlaceer1@help.de','Eins','Supporter'),
							('SuppPlaceer2@help.de','Zwei','Supporter'),
							('SuppPlaceer3@help.de','Drei','Supporter'),
							('benutzer1@mail.de','Test1','Benutzer'),
							('benutzer2@mail.de','Test2','Benutzer'),
							('benutzer3@mail.de','Test3','Benutzer'),
							('benutzer4@mail.de','Test4','Benutzer'),
							('Ackerman23@gmx.net','Ben','Ackermann'),
							('L.Barth@web.de','Luca','Barth'),
							('nixPeiler@gibts.net','Paul','Dietz'),
							('luEck@leckt.net','Lukas ','Eckbauer'),
							('lsadflkjsadflj@gmx.de','Finn','Conradi'),
							('Jonas@Fechner.de','Jonas','Fechner'),
							('habkeinenplan@googlEMail.de','Leon','Gerlach'),
							('Zwerz89@gmx.de','Luis ','Haase'),
							('Thunderstrom@hotmail.de','Maximilian','Junken'),
							('nichtverwand@Helmut.de','Felix','Kohl'),
							('Lachnicht@Held.de','Tim','Lachmann'),
							('Affenkopf3@falsche.fr','Elias','Mende'),
							('Apfel19@Obst.de','Max','Neureuther'),
							('Miauw@gmx.de','Mia','Oderwald'),
							('girl22@datemich.de','Emma','Patberg'),
							('A.Reu@chat.de','Anna','Reuter'),
							('Schulzi_Lea@googlEMail.de','Lea','Schulz'),
							('Sunshine87@lycos.de','Sophia','Trapp'),
							('Anna.Ullmann@Schneefall.com','Anna','Ullmann'),
							('Lena24@Single.com','Lena','Vogt'),
							('Pizzawoman@Wagner.com','Melanie','Wagner'),
							('Linchen@Zobel.com','Lina','Zobel');


INSERT INTO ShippingTab (Price, Shipping) VALUES	

							(0.001, 'Brief'),
							(4.99, 'DHL-Paekchen'),
							(4.50, 'Hermes'),
							(9.99, 'DHL-Paket');
							
INSERT INTO PaymentTab (Price, Payment) VALUES	

							(0.001, 'Bank'),
							(1.99, 'PayPal'),
							(0.99, 'Visa');

INSERT INTO ShippingAddressTab (Street, PLZ, Place, Country) VALUES	

							('Broadway 11', 44122, 'New York', 'USA'),
							('Schlossalle 22', 80122, 'Hamburg' , 'Deutschland'),
							('Hauptweg 33', 66622, 'Goslar', '');

INSERT INTO OrderTab (UserID, ShipID, PayID, TotalPrice, AddressID, Date, Sent, ShippingID) VALUES 	
						
							(1, 2, 1, 11.11, 1, '04-01-2013', 'true', 1),
							(2, 2, 2, 22.22, 2, '04-02-2013', 'false', 2),
							(3, 3, 3, 33.33, 3, '01-03-2013', 'true', 3);

INSERT INTO AgbTab (UserID, AGBaccepted) VALUES 	

							(1,'true'),
							(2,'true'),
							(3,'true'),
							(4,'true'),
							(5,'true'),
							(6,'true'),
							(7,'true'),
							(8,'true'),
							(9,'true'),
							(10,'true'),
							(11,'true'),
							(12,'false'),
							(13,'true'),
							(14,'true'),
							(15,'true'),
							(16,'true'),
							(17,'true'),
							(18,'true'),
							(19,'true'),
							(20,'true'),
							(21,'true'),
							(22,'true'),
							(23,'true'),
							(24,'true'),
							(25,'true'),
							(26,'true'),
							(27,'true'),
							(28,'true'),
							(29,'true'),
							(30,'true'),
							(31,'true'),
							(32,'true');
							
							

INSERT INTO AddressTab (UserID, Street, PLZ, Place, Country) VALUES	

							(1,'Theaterstrasse 36',13228,'Super','User'),
							(2,'Museumsstrasse 6',65529,'Eins','Admin'),
							(3,'Opernplatz 4',54969,'Zwei','Admin'),
							(4,'Nordbahnhof 50',05191,'Eins','Supporter'),
							(5,'Lessingstrasse 44',79434,'Zwei','Supporter'),
							(6,'Schillerstrasse 440',29152,'Drei','Supporter'),
							(7,'Wasserwerk 80',61243,'Test1','Benutzer'),
							(8,'Goethestrasse 10',12440,'Test2','Benutzer'),
							(9,'Berliner Strasse 32',59980,'Test3','Benutzer'),
							(10,'Rathausplatz 52',77008,'Test4','Benutzer'),
							(11,'Wiener Strasse 28',18221,'Ben','Ackermann'),
							(12,'Hauptstrasse 9',84517,'Luca','Barth'),
							(13,'Muenchner Strasse 13',92993,'Paul','Dietz'),
							(14,'Bahnhofstrasse 56',65332,'Lukas ','Eckbauer'),
							(15,'Westbahnhof 5',34056,'Finn','Conradi'),
							(16,'Hauptbahnhof 1',62945,'Jonas','Fechner'),
							(17,'Neue Strasse 24',71536,'Leon','Gerlach'),
							(18,'Hafenstrasse 2',37624,'Luis ','Haase'),
							(19,'Parkstrasse 7',33197,'Maximilian','Junken'),
							(20,'Elektrizitaetswerk 49',17262,'Felix','Kohl'),
							(21,'Seestrasse 200',98496,'Tim','Lachmann'),
							(22,'Schlossallee 1',58036,'Elias','Mende'),
							(23,'Suedbahnhof 500',85067,'Max','Neureuther'),
							(24,'Poststrasse 16',17845,'Mia','Oderwald'),
							(25,'Elisenstrasse 12)',36644,'Emma','Patberg'),
							(26,'Chausseestrasse 20',71206,'Anna','Reuter'),
							(27,'Turmstrasse 80',34978,'Lea','Schulz'),
							(28,'Badstrasse 40',73182,'Sophia','Trapp'),
							(29,'Samelsonweg 35',56660,'Anna','Ullmann'),
							(30,'Marienburgenalle 3',07507,'Lena','Vogt'),
							(31,'Buehlerweg 5',14294,'Melanie','Wagner'),
							(32,'Hindenburgplatz 37',86691,'Lina','Zobel');




INSERT INTO AuthTab (UserID, PW) VALUES 		

							(1,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(2,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(3,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(4,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(5,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(6,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(7,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(8,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(9,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(10,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(11,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(12,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(13,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(14,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(15,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(16,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(17,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(18,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(19,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(20,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(21,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(22,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(23,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(24,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(25,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(26,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(27,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(28,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(29,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(30,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(31,'bbb9d60a4eac9e30b87521d46e4a538d'),
							(32,'bbb9d60a4eac9e30b87521d46e4a538d');

INSERT INTO RightsTab (UserID, AdminRight, Supporter) VALUES	

							(1, 'true', 'true'),
							(2, 'true', 'true'),
							(3, 'true', 'true'),
							(4, 'false', 'true'),
							(5, 'false', 'true'),
							(6, 'false', 'true'),
							(7, 'false', 'false'),
							(8, 'false', 'false'),
							(9, 'false', 'false'),
							(10,'false', 'false'),
							(11, 'false', 'false'),
							(12, 'false', 'false'),
							(13, 'false', 'false'),
							(14, 'false', 'false'),
							(15, 'false', 'false'),
							(16, 'false', 'false'),
							(17, 'false', 'false'),
							(18, 'false', 'false'),
							(19, 'false', 'false'),
							(20, 'false', 'false'),
							(21, 'false', 'false'),
							(22, 'false', 'false'),
							(23, 'false', 'false'),
							(24, 'false', 'false'),
							(25, 'false', 'false'),
							(26, 'false', 'false'),
							(27, 'false', 'false'),
							(28, 'false', 'false'),
							(29, 'false', 'false'),
							(30, 'false', 'false'),
							(31, 'false', 'false'),
							(32, 'false', 'false');
							
							
INSERT INTO ManufacturerTab (Manufacturer) VALUES 	
						
							('Lian Li'),
							('Techsolo'),
							('MS-Tech'),
							('HKC'),
							('CoolerMaster'),
							('HIS'),
							('Asus'),
							('PowerColor'),
							('Palit'),
							('ZOTAC'),
							('ASRock'),
							('Gigabyte'),
							('Intel'),
							('AMD'),
							('be quiet!'),
							('Xilence'),
							('Cougar'),
							('AeroCool'),
							('Microsoft'),
							('Kaspersky'),
							('Symantec'),
							('Avira'),
							('Bitdefender'),
							('Acronis'),
							('Nero'),
							('Lexware'),
							('Paragon'),
							('Corel'),
							('Adobe'),
							('Data Becker'),
							('Franzis'),
							('Steinberg'),
							('Lenovo'),
							('Hewlett Packard'),
							('Dell'),
							('Toshiba'),
							('Samsung'),
							('Huawei'),
							('Intenso'),
							('Sony'),
							('Shuttle'),
							('Sapphire'),
							('Audioline'),
							('Tiptel'),
							('Telekom'),
							('Doro'),
							('Gigaset'),
							('LG'),
							('Nokia'),
							('Blaupunkt'),
							('Garmin'),
							('TomTom'),
							('Linksys'),
							('Auerswald'),
							('Cisco'),
							('Alcatel'),
							('Canon'),
							('Nikon'),
							('Casio'),
							('Olympus'),
							('Philips'),
							('Nintendo'),
							('Activision'),
							('EA');

INSERT INTO CategoryTab (Category, Subcategory, Attribut1, Attribut2, Attribut3, Attribut4, Attribut5, Attribut6, Attribut7) VALUES 	
--Höhe Breite Länge ...						
							('Hardware','Gehaeuse','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Hardware','Grafikkarten','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Hardware','Mainboards','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Hardware','Prozessoren','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Hardware','Netzteil','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Software','OS','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Software','Office','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Software','Sicherheit','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Software','Utilities','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Software','Sonstiges','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Komplettsysteme','Netbook','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Komplettsysteme','Notebook','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Komplettsysteme','Tablet','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Komplettsysteme','PCMarke','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Komplettsysteme','Barebone','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Kommunikation','AnrufbeantwPlaceer','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Kommunikation','Festnetz','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Kommunikation','Handy','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Kommunikation','Navigation','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Kommunikation','VoIP','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Entertainment','Kamera','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Entertainment','DVD-BlueRay','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Entertainment','Spielkonsole','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Entertainment','TV','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7'),
							('Entertainment','Spiele','Attribut1','Attribut2','Attribut3','Attribut4','Attribut5','Attribut6','Attribut7');
							


INSERT INTO ArticleTab (ArtName, Price, CategoryID, Description, Quantity, ManufacturerID, Liked, Offer, Discount) VALUES

							('Lian Li PC-Q08B Wuerfel ohne Netzteil schwarz',93.31,1,'Das schwarz geb&uuml;rstete Aluminium Geh&auml;use besticht durch seine Schlichtheit im Design. F&uuml;r einen besonderen optischen Anreiz sorgt der blau leuchtende 140mm L&uuml;fter in der Vorderseite. Ein weiterer 120mm L&uuml;fter befindet sich im Deckel. Das Geh&auml;use bietet ausreichend Platz f&uuml;r ein externes 5,25&quot; (13,34cm) Laufwerk, wahlweise DVD oder BluRay, und gleich bis zu sechs interne 3,5&quot; (8,89cm) Festplatten. Die Montage der Festplatten erfolgt in zwei getrennten K&auml;figen. Zwei in der Front angebrachte USB 3.0 Ports erm&ouml;glichen den Anschluss weiterer Hardware.',10,1,0,'true',7.00),
('Techsolo TC-85S Midi Tower 400 Watt schwarz/silber',29.61,1,'Das TC-85 ist ein Midi Tower mit besonderem Design. Es ist schlicht und zugleich edel. Dank des Designs und der kompakten Abmessungen f&uuml;gt es sich in jedes Ambiente und bietet dennoch ausreichend Platz f&uuml;r Ihre Komponenten. F&uuml;r ATX, Micro ATX und Mini ITX Mainboards geeignet.',10,2,0,'true',0.00),
('MS-Tech CA-011 Desktop 400 Watt schwarz/rot',36.63,1,'Das CA-011 ist ein Slimline Geh&auml;use in roter Klavierlackoptik f&uuml;r Micro ATX Mainboards mit integriertem 400 Watt Netzteil. Das Geh&auml;use verf&uuml;gt zudem &uuml;ber Front HD Audio und Front USB Anschl&uuml;sse. Durch die kompakten Abmessungen k&ouml;nnen nur Micro ATX Mainboards und Low-Profile Steckkarten verbaut werden.',10,3,23,'false',0.00),
('HKC 7802GDR Midi Tower 420 Watt schwarz',40.43,1,'Effiziente Geh&auml;usebel&uuml;ftung: Zur besseren Entl&uuml;ftung des Geh&auml;uses ist ein 120 mm L&uuml;fter an der Front installiert. Ein weiterer 80 mm L&uuml;fter in der Seitenwand und zwei 80mm L&uuml;fter an der R&uuml;ckseite k&ouml;nnen optional montiert werden. Front-Access: In der Front befinden sich Front Access Elemente in Form von einem eSATA, zwei USB 2.0 und Audio Anschl&uuml;ssen.',10,4,0,'false',20.00),
('CoolerMaster Centurion 534 Plus Midi Tower ohne Netzteil schwarz/silber',59.26,1,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,5,0,'false',0.00),
('1024MB HIS Radeon HD 7750 iSilence Passiv PCIe 3.0 x16 (Retail)',94.72,2,'Basierend auf der preisgekr&ouml;nten GCN-Architektur sind GPUs der AMD Radeon HD 7700 Serie mit dem branchenweit ersten 28 nm-GPU-Design f&uuml;hrend. Vollgepackt mit intelligenten Leistungsmerkmalen wie z.B. PCI Express 3.0, der effizienten AMD ZeroCore Energietechnologie oder der AMD Eyefinity Techologie f&uuml;r Aufl&ouml;sungen von mehr als 5.760 x 1.080, sind dieses die weltweit fortschrittlichsten Grafikkarten. Effizienz. Flexibilit&auml;t. Leistung. Das ist die DNA der AMD Radeon HD 7750 - der weltweit fortschrittlichsten Grafikkarte. Die AMD Eyefinity Technologie ist da, mit kompletter Unterst&uuml;tzung f&uuml;r Stereo 3D, universeller Rahmenkompensation und brandneuen Anzeigekonfigurationen. Ebenso k&ouml;nnen Sie mit dem PCI Express 3.0-Standard und Multi-GPU-Konfigurationen mit AMD CrossFire Technologie die Konkurrenz mit der revolution&auml;ren AMD Radeon HD 7750 ganz leicht &uuml;bertrumpfen. Sorgen Sie f&uuml;r h&ouml;here Taktraten und schnelleres Gaming mit der AMD PowerTune Technologie der AMD Radeon HD 7750 Grafikkarte. Noch schnelleres Abrufen und Bearbeiten von Daten als jemals zuvor mit AMD Anwendungsbeschleunigung mit beispielloser 28 nm-GCN-Architektur. Der Markt ist noch nicht bereit f&uuml;r 4K-Video - Radeon schon. Dank voller Unterst&uuml;tzung f&uuml;r HDMI (mit 4K) und DisplayPort 1.2 HBR2 ist AMD Radeon HD 7750 bereit f&uuml;r Quad-HD.',10,6,343,'false',0.00),
('512MB Asus Radeon HD 5450 Silent Series Low Profile V2 Passiv PCIe 2.1 x16 (Retail)',26.73,2,'Die ATI Radeon&trade; HD 5450 Grafikkarte l&auml;sst im Bereich Gaming und Entertainment keine W&uuml;nsche offen. Erweitern Sie Ihr Sichtfeld mit der ATI Eyefinity Technologie. Beschleunigen Sie mit der ATI Stream Technologie anspruchsvolle Anwendungen, und erreichen Sie mit Ihrem Computer mehr als jemals zuvor.',10,7,0,'false',0.00),
('6144MB PowerColor Radeon HD 7990 Devil 13 Edition Aktiv PCIe 3.0 x16 (Retail)',902.33,2,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,8,353,'false',40.00),
('4096MB Palit GeForce GTX 680 JetStream Aktiv PCIe 3.0 x16 (Retail)',526.09,2,'Der GeForce GTX 680 Prozessor ist ein schneller und fortschrittlicher Grafikprozessor, den NVIDIA je gebaut hat. Aber damit nicht genug. Die GPU Boost Technologie steigert dynamisch die Taktfrequenz f&uuml;r maximale Leistung. Adaptive V-Sync sorgt f&uuml;r ideale, ruckelfreie Frameraten und NVIDIA Surround erm&ouml;glicht Gaming auf drei Bildschirmen mit nur einer Grafikkarte. Bisher liefen Grafikprozessoren bei 3D Games, mit einer festen Taktfrequenz, selbst wenn sie das Potenzial f&uuml;r h&ouml;here Taktungen hatten. GPU Boost &uuml;berwacht st&auml;ndig die Arbeitslast des Grafikprozessors und steigert nach M&ouml;glichkeit die Taktfrequenz. Der Grafikprozessor l&auml;uft immer mit optimaler Leistung und liefert maximale Frameraten. Die leistungsstarke Palit GeForce GTX 680-Architektur bietet mehr als modernste Funktionen und Technologien. Sie bietet eine einmalige Leistung und wird die Art und Weise des Spielerlebnis sowohl aktueller als auch kommender Spitzentitel nachhaltig ver&auml;ndern!',10,9,6,'false',20.00),
('1024MB ZOTAC GeForce GTS 450 ECO Edition Aktiv PCIe 2.0 x16 (Retail)',67.2,2,'Die ZOTAC&reg; GeForce&reg; GTS 450 ECO Edition zeichnet sich durch eine herausragende Energieeffizienz mit einem bis zu 33 Prozent niedrigeren Energieverbrauch aus. Ausgestattet mit 192 Prozessorkernen und dem &uuml;ber 128-bit angebundenen 1024 MB gro&szlig;en DDR3 Speicher bietet die GTS 450 ECO dabei eine exzellente Leistungsf&auml;higkeit sowohl in den neusten DirectX&reg; 11 Spielen als auch in CUDA&trade; unterst&uuml;tzten Applikationen. Die ZOTAC&reg; GeForce&reg; GTS 450 ECO Edition im Single-Slot Design ist zudem die perfekte Grafikkarte f&uuml;r Heimkino-Liebhaber und &uuml;berzeugt mit starken Home-Theater-PC Features wie Hardware-Video-Beschleunigung zur Dekodierung von High-Definition-Videos, Dolby&reg; TrueHD und DTS-HD Master Audio&trade; Bitstreaming- sowie HDMI 1.4a Unterst&uuml;tzung.',10,10,0,'false',0.00),
('ASRock Q77M vPro Intel Q77 So.1155 Dual Channel DDR3 mATX Retail',90.01,3,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,11,0,'false',5.00),
('Gigabyte GA-F2A55M-DS2 AMD A55 So.FM2 Dual Channel DDR3 mATX Retail',50.03,3,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,12,7979,'true',0.00),
('Asus Crosshair V Formula-Z V2.0 AMD 990FX So.AM3+ Dual Channel DDR ATX Retail',207.26,3,'Das Republic of Gamers AM3+ Gaming Mainboard verf&uuml;gt zus&auml;tzlich &uuml;ber exklusive ROG Technologien, die Hardcore-Gamer eine leistungsstarke und stabile Windows 8 basierte AMD-Plattform bieten. Dazu z&auml;hlen Gaming und Overclocking-spezifische Features wie ROG Extreme Engine Digi+ II Digital Power Control zur pr&auml;zisen digitalen Leistungsreglung von CPU und DRAM und gleichzeitiger Verbesserung der &Uuml;bertaktungsm&ouml;glichkeiten. F&uuml;r besten Sound im Spiel ist die auf einer eigenen Platine basierende Soundl&ouml;sung SupremeFX III verbaut. Die Soundqualit&auml;t wird durch die SupremeFX Shielding-Technologie verbessert, da der Soundchip durch eine Aluminiumkappe vor st&ouml;renden elektromagnetischen Beeinflussungen (EMI) gesch&uuml;tzt wird. Die ROG GameFirst II Software optimiert den Netzwerkverkehrs bei der Daten&uuml;bertragung und &uuml;ber den neu integrierten EZ Modus steht eine intuitive Benutzeroberfl&auml;che bereit, &uuml;ber die die Bandbreitenpriorisierung schneller verwaltet werden kann.',10,7,0,'true',0.00),
('ZOTAC NM10-ITX WiFi Intel NM10 So.BGA Single Channel DDR2 Mini-ITX Retail',86.77,3,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,10,8,'false',0.00),
('Asus Maximus V Gene Intel Z77 So.1155 Dual Channel DDR3 mATX Retail',164.43,3,'Das Maximus V GENE f&uuml;hrt die Republic of Gamers Reihe in die f&uuml;nfte Generation der erfolgreichen Maximus-Serie. Das Micro-ATX Kraftpaket basiert auf dem neuesten Intel Z77 Chipsatz, verf&uuml;gt &uuml;ber den aktuellen Sockel 1155 f&uuml;r Intel Prozessoren der 3. und 2. Generation, sowie PCI-Express Gen-3 f&uuml;r Einzel-oder Multi-GPU Unterst&uuml;tzung. Das Republic of Gamers Team hat das in schwarz und rot gehaltene Maximus V GENE mit exklusiven Features wie Extreme Engine DIGI+ II, SupremeFX III Gaming Audio, Intel Ethernet mit ROG GameFirst und einer mPCIe Combo Karte ausgestattet.',10,7,0,'false',0.00),
('Intel Celeron G460 1x 1.80GHz So.1155 BOX',33.13,4,'Computer mit Intel Celeron Prozessoren sind ideal f&uuml;r allt&auml;gliche Aufgaben, ob zu Hause, in der Schule oder im B&uuml;ro.',10,13,0,'false',0.00),
('Intel Core i5 3570K 4x 3.40GHz So.1155 BOX',214.64,4,'Der Intel Core i5 Desktop-Prozessor sorgt im Beruf und in der Freizeit f&uuml;r deutlich mehr PC-Power und Geschwindigkeit beim Multitasking. Er passt sich bei erh&ouml;htem Leistungsbedarf intelligent an. Selbst bei anspruchsvollen Anwendungen - wie Spielen oder Bildbearbeitung - h&auml;lt er mit Ihnen Schritt.',10,13,79,'false',3.00),
('Intel Pentium G850 2x 2.90GHz So.1155 BOX',68.38,4,'Der Intel Pentium Prozessor G840 basiert auf der neuen 32nm-Sandy-Bridge-Architektur und ist eine native Dual-Core-CPU mit integriertem Grafikkern (Intel&reg; HD 2000). Der integrierte Speichercontroller unterst&uuml;tzt DDR3-Speicher bis 1333 MHz. Die eingebaute GPU l&auml;uft mit 850 Mhz (max. 1100 mit Turbo) und teilt sich den gemeinsamen, 3 MB gro&szlig;en L3-Cache mit der CPU.',10,13,0,'false',0.00),
('AMD A8 Series A8-5600K 4x 3.60GHz So.FM2 BOX',88.45,4,'Entscheiden Sie sich f&uuml;r AMD und damit f&uuml;r die Aufnahme der weltweit einzigen Accelerated Processing Unit (APU) in Ihr n&auml;chstes PC-Projekt. Die AMD Prozessoren der A-Serie f&uuml;hren CPU und GPU auf einem energieeffizienten Chip zusammen. Das Ergebnis: erstklassige Leistung und niedriger Stromverbrauch.',10,14,0,'false',0.00),
('AMD FX Series FX-6300 6x 3.50GHz So.AM3+ BOX',115.05,4,'Stellen Sie Ihre Konkurrenz in den Schatten mit der unb&auml;ndigen Leistung eines AMD FX Prozessors. Unlocked - standardm&auml;&szlig;ig - und die alles zum Kampfpreis. AMD FX Prozessoren bieten Ihnen mit annehmbarer Leistung un hoher Geschwindigkeit Entlastung f&uuml;rs Budget.',10,14,799,'false',0.00),
('300 Watt be quiet! System Power 7 Non-Modular 80 Bronze',28.51,5,'Der Markt f&uuml;r PC-Komplettsysteme ist stark umk&auml;mpft. Die Kunden von System-Integratoren (SI) stellen hohe Anforderungen und sind auf der Suche nach dem attraktivsten Preis-Leistungsverh&auml;ltnis. Deswegen hat be quiet! jetzt die neue System Power 7 Serie entwickelt, die speziell auf die Bed&uuml;rfnisse von System-Integratoren abgestimmt ist. Das System Power 7 300W bietet die bestm&ouml;gliche Kombination aus Leistung, Laufruhe, Ausstattung und Effizienz und damit viele Vorteile f&uuml;r System Integratoren, mit h&ouml;chstm&ouml;glicher Kompatibili&auml;t, einem Maximum an 12V Leistung und einer felsenfesten Spannungsstabilit&auml;t. Zertifiziert mit 80PLUS Bronze erm&ouml;glicht es das Zusammenstellen kosteneffektiver Systeme mit &uuml;berlegener Leistung - ein wertvolles Unterscheidungsmerkmal von Produkten mit immer &auml;hnlicher werdender Ausstattung.',10,15,0,'false',0.00),
('400 Watt Xilence RedWing R3 Non-Modular 80',29.75,5,'Die dritte Generation Xilence Netzeile - aufregendes Design, neuste Technik und top Qualit&auml;t. Beim aktuellen Revisionswechsel wurden alle Netzteilserien komplett &uuml;berarbeitet. Das Resultat &uuml;berzeugt nicht nur durch hocheffiziente Technik, sondern auch durch neues Design und eine noch bessere Ausstattung. Die Anschl&uuml;sse wurden auf aktuelle Systeme abgestimmt und durch die erh&ouml;hte Energieeffizienz sind die Powerpakete nun noch k&uuml;hler und leiser.',10,16,7809,'false',5.00),
('550 Watt Cougar CMX Modular 80 Bronze',81.98,5,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,17,0,'true',0.00),
('430 Watt be quiet! Pure Power CM Modular 80 Bronze',54.63,5,'Das Pure PowerTM L8 430W CM verbessert so gut wie jede PC-Konfiguration zugunsten der Umwelt, des Geldbeutels und der Ohren. Es ist die ideale Basis f&uuml;r moderne und anspruchsvolle Hardware-Komponenten. Ausgestattet mit modularem Kabelmanagement, bietet das Pure Power L8 430W grundsolide Spannung, unglaubliche Zuverl&auml;ssigkeit, hohe Effizienz und einen au&szlig;erordentlich leisen Betrieb kurz gesagt die bestm&ouml;gliche Kombination von Ausstattung, Leistung und Qualit&auml;t zu einem &auml;u&szlig;erst attraktiven Preis. Au&szlig;erordentlich leiser Betrieb dank einer Vielzahl sorgf&auml;ltiger Verbesserungen, einschlie&szlig;lich der Nutzung eines speziell entwickelten, ger&auml;uschoptimierten 120-mm-L&uuml;fters 430 Watt Dauerleistung bieten umfangreiche Leistungsreserven f&uuml;r Zeiten, in denen Sie Ihrem PC wirklich alles abverlangen Kabelmanagement mit gro&szlig;er Kabelreichweite vereinfacht die Installation von Komponenten, reduziert Kabelsalat, erleichtert die Bel&uuml;ftung und verbessert die K&uuml;hlung 80PLUS Bronze-Zertifizierung mit einer Effizienz von bis zu 88 % erm&ouml;glichen es Ihnen, mit der gleichen Leistung mehr Arbeit zu erledigen und Ihre Stromrechnung zu reduzieren AMD CrossfireX-Zertifizierung erlaubt Ihnen die Zusammenstellung leistungsf&auml;higer Multi-GPU-Systeme.',10,15,0,'true',0.00),
('1100 Watt AeroCool Strike-X Modular 80 Gold',133.54,5,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,18,0,'false',7.00),
('Microsoft Windows 7 Professional inkl. SP1 64 Bit Deutsch OEM SB',114.59,6,'Microsoft hat Windows 7 nach Ihren Vorstellungen und Ideen entwickelt: Sie w&uuml;nschen sich einen Windows-PC, der schnell und zuverl&auml;ssig arbeitet und einfach zu bedienen ist. Windows 7 enth&auml;lt eine Reihe innovativer Funktionen und neuer Technologien, die genau diesem Ziel folgen.',10,19,575,'false',0.00),
('Microsoft Windows 8 32 Bit Dänisch OEM/SB',92.92,6,'Bei der Entwicklung von Windows 8 stand der Anwender im Fokus. Unabh&auml;ngig davon, ob Windows 8 auf einem Tablet, Notebook oder Desktop-PC verwendet wird - das moderne, schnelle und stabile Betriebssystem ist f&uuml;r jeden Kunden die richtige Wahl. Das hochfunktionale Design der neuen Benutzeroberfl&auml;che erm&ouml;glicht blitzschnellen Zugriff auf alle wichtigen Elemente, so dass man weniger Zeit mit Suchen verbringt und mehr Zeit f&uuml;r Produktivit&auml;t, Kommunikation und Entertainment gewinnt.',10,19,0,'false',0.00),
('Microsoft Windows 8 Pro 32/64 Bit Deutsch Upgrade',48.74,6,'Bei der Entwicklung von Windows 8 stand der Anwender im Fokus. Unabh&auml;ngig davon, ob Windows 8 auf einem Tablet, Notebook oder Desktop-PC verwendet wird - das moderne, schnelle und stabile Betriebssystem ist f&uuml;r jeden Kunden die richtige Wahl. Das hochfunktionale Design der neuen Benutzeroberfl&auml;che erm&ouml;glicht blitzschnellen Zugriff auf alle wichtigen Elemente, so dass man weniger Zeit mit Suchen verbringt und mehr Zeit f&uuml;r Produktivit&auml;t, Kommunikation und Entertainment gewinnt.',10,19,0,'false',0.00),
('Microsoft Windows 7 Home Premium inkl. SP1 32 Bit Deutsch OEM SB',80.73,6,'Mit Windows 7 Home Premium ist es ganz einfach, ein Heimnetzwerk zu erstellen und alle Lieblingsfotos, -videos und Musiktitel freizugeben. Sie k&ouml;nnen sogar TV-Sendungen anschauen, anhalten, zur&uuml;ckspulen und aufzeichnen. Windows 7 Home Premium bietet Ihnen beste Unterhaltung am PC. Microsoft Windows 7 SP1 ist ein Update f&uuml;r Windows 7, die zuvor ver&ouml;ffentlichten Updates f&uuml;r bestimmte Probleme f&uuml;r Zuverl&auml;ssigkeit, Leistung und Kompatibilit&auml;t enth&auml;lt.',10,19,456,'false',0.00),
('Microsoft Windows 7 Ultimate 32/64 Bit Deutsch Retail',267.19,6,'Windows 7 ist das neue Betriebssystem von Microsoft. Die besten Elemente von Windows Vista wurden um tolle neue Technologien und Funktionen erweitert. So erwartet Sie ein bedienerfreundliches Produkt, bei dem auf Sicherheit und Kompatibilit&auml;t zu Hard- und Software geachtet wurde. Mit Windows 7 stellt sich Microsoft dem Anspruch ein Betriebssystem ganz nach den W&uuml;nschen der Kunden zu entwickeln.',10,19,0,'false',40.00),
('Microsoft Office University 2010 32/64 Bit Deutsch 1 User PC (DVD)',80.85,7,'Die komplette Produktivit&auml;ts-Suite f&uuml;r Studierende und Lehrende an Hochschulen. Verwenden Sie die sieben enthaltenen, perfekt aufeinander abgestimmten Anwendungen zum Gestalten von Dokumenten aller Art, Organisieren von Datenbest&auml;nden, Verwalten von E-Mails, Kontakten, Terminen und Notizen sowie zum Pr&auml;sentieren Ihrer Studien. Profitieren Sie sp&auml;ter im Berufleben von Ihren Kenntnissen &uuml;ber die weltweit meistverwendete Office-Suite.',10,19,0,'false',0.00),
('Microsoft Office 2010 Professional 32/64 Bit Deutsch 1 User PC (DVD)',496.43,7,'Microsoft Office Professional 2010 - Full Package Product - 1 PC - DVD - Win - Deutsch - 32/64-bit - enth&auml;lt: Microsoft Excel, Microsoft Powerpoint, Microsoft Word, Microsoft Outlook, Microsoft OneNote, Microsoft Publisher, Microsoft Access.',10,19,0,'false',0.00),
('Microsoft Word 2010 32/64 Bit Deutsch 1 User PC (DVD)',134.11,7,'32- und 64-Bit/ 2010/ deutsch/ Vollversion/ Box/ Datentr&auml;ger: DVD/ Win Vista, Windows 7.0, Win XP',10,19,547,'false',5.00),
('Microsoft Office 365 Home Premium 32/64 Bit Englisch 1 User PC (PKC)',82.67,7,'Microsoft hat ein neues Office-Paket f&uuml;r Mac und Windows bereitgestellt. Neben Office 2013 gibt es Office 365 Home, eine Cloud-angebundene Software f&uuml;r Privatanwender, die auf bis zu f&uuml;nf Ger&auml;ten nutzbar ist.',10,19,0,'true',0.00),
('Microsoft Office MAC Home & Business 2011 [DE] PKC',216.98,7,'Office Home &amp; Business 2013: ein Plus an Produktivit&auml;t zuhause und im B&uuml;ro. Diese Edition umfasst die aktuellsten Versionen der bew&auml;hrten und zuverl&auml;ssigen Office-Anwendungen Word, Excel, PowerPoint, OneNote und Outlook. Office Home &amp; Business 2013 kann auf einem privat oder gesch&auml;ftlich genutzten PC installiert werden. Die moderne Bedienoberfl&auml;che unterst&uuml;tzt die Touch-Steuerung, die Stifteingabe sowie Maus und Tastatur. Mit diesen Werkzeugen haben Sie B&uuml;ro und Privatleben perfekt im Griff - ganz nach Wunsch. Sie erstellen Dokumente, Tabellen und Pr&auml;sentationen in professioneller Qualit&auml;t. Nun k&ouml;nnen Sie &uuml;berall und jederzeit arbeiten. Dazu brauchen Sie lediglich einen Computer mit einem Webbrowser und den Office Web Apps. Und durch die zuverl&auml;ssige Kompatibilit&auml;t mit Office f&uuml;r Windows gelingt auch die Kommunikation und Weitergabe Ihrer Dateien an andere m&uuml;helos. Konzipiert und lizenziert f&uuml;r den anspruchsvollen pers&ouml;nlichen Gebrauch, f&uuml;r die Arbeit von zu Hause und f&uuml;r kleine Unternehmen. Enth&auml;lt Outlook f&uuml;r Mac 2011.',10,19,0,'true',0.00),
('Kaspersky Lab AntiVirus 2013 DVD German (Upgrade)',13.85,8,'Kaspersky Anti-Virus 2013 (Upgrade) ist die Basis Ihrer PC-Sicherheit und bietet zuverl&auml;ssigen Schutz in Echtzeit vor Viren, Spyware und anderen Internet-Bedrohungen. Kaspersky Anti-Virus 2013 ist die Basis Ihrer PC-Sicherheit und bietet Echtzeit-Schutz sowohl vor bekannten als auch neuen Internet-Bedrohungen. Die Software arbeitet still im Hintergrund, mit intelligenten Scans und kleinen, regelm&auml;&szlig;igen Updates. Dabei wird Ihr PC proaktiv gesch&uuml;tzt, ohne ausgebremst zu werden - und Sie k&ouml;nnen um die Sicherheit Ihres PCs und Ihrer Daten v&ouml;llig unbesorgt sein.',10,20,869,'false',0.00),
('Symantec Norton Antivirus 2012',20.14,8,'Norton AntiVirus 2012 bietet leistungsstarker Antivirus- und Spyware-Schutz - &uuml;berzeugend schnell. 1 User/ 2012/ deutsch/ Vollversion/ Minibox/ Datentr&auml;ger: CD/ Win',10,21,0,'false',0.00),
('Avira Antivirus Premium 2012 - 2 User',14.87,8,'Avira Antivirus Premium 2012 sorgt mit seinen ma&szlig;geblichen Funktionen daf&uuml;r, dass Sie sich nun dank AntiPhishing und dem Schutz Ihrer privaten Daten unbeschwert in Ihrer gesch&auml;ftigen Online-Welt bewegen k&ouml;nnen.',10,22,0,'false',3.00),
('Bitdefender Internet Security 2013 3User (deutsch)(PC)',37.54,8,'Bitdefender Internet Security 2013 - Komfortschutz f&uuml;r Ihren PC! Die Hauptaufgabe von Bitdefender Internet Security besteht darin Ihren PC vor Viren, Spyware, Spam und Identit&auml;tsdiebstahl zu sch&uuml;tzen. Zudem bietet Ihnen die neue Virenschutzsoftware eine praktische Kindersicherung, einen Schutz Ihrer WLAN-Verbindung &uuml;ber eine Firewall sowie den Schutz Ihrer Privatsph&auml;re in sozialen Netzwerken und eine Vorauswarnung vor gef&auml;hrlichen Webseiten in den Suchergebnissen der Suchmaschinen. Bitdefender Internet Security 2013 ist mit dem neuen Betriebssystem Windows 8 kompatibel, welches im Oktober 2012 auf den Markt kommen wird. Bitdefender Internet Security 2012 kombiniert Virenschutz, Spam-Schutz, Phishing-Schutz, Firewall, Kindersicherung und Sicherheit in sozialen Netzwerken in einer L&ouml;sung, die idealen Hintergrundschutz f&uuml;r Familien mit Internet-Anschluss bietet.',10,23,0,'false',0.00),
('Acronis TrueImage Home 2013 FamilyPack DT. MiniBOX',47.94,8,'Betrachten Sie Backup mal aus ganz anderer Sicht - mit moderner Synchronisierungstechnologie. Cloud Storage. Das True Image 2013 by Acronis unterst&uuml;tzt jetzt auch Synchronisierung mit mobilen Endger&auml;ten &uuml;ber kostenlose Apps f&uuml;r iOS und Android. Probieren Sie es ganz einfach aus-, egal, ob Sie es zum ersten Mal installieren oder von einer Vorg&auml;ngerversion upgraden. True Image 2013 by Acronis sichert Ihre Fotos, Dokumente, Musik, Mails, Programme, Kontakte, Kalender und vieles mehr. Es speichert Ihre Daten an einem gesch&uuml;tzten Ort online und erm&ouml;glicht Synchronisierung mit Ihren mobilen Endger&auml;ten. True Image 2013 by Acronis ist sicher, zuverl&auml;ssig und einfach.',10,24,5,'false',1.00),
('Ahead Nero 12 OEM Essentials',7.90,9,'Mit Nero 12 ist es einfach, Fotoalben, Diashows, Musik-Playlists und mehr auf Ihre verschiedenen Ger&auml;te zu streamen. Projekte oder Kompilationen m&uuml;ssen nur einmal erstellt werden, bevor sie auf XBOX 360&trade;, PS3&trade;, iPad&reg;, Android-Tablets, PCs, digitale Medienadapter, streamingf&auml;hige Fernsehger&auml;te oder andere Ger&auml;te mit DLNA- oder UPnP-Unterst&uuml;tzung gestreamt werden k&ouml;nnen.',10,25,45,'false',0.00),
('Lexware QuickSteuer 2013',9.99,9,'Die einfachste Art, Steuern zu sparen - QuickSteuer 2013. Dank der Schritt-f&uuml;r-Schritt-Anleitung gelangen Sie m&uuml;helos durch die Steuererkl&auml;rung - und das sogar ohne Vorkenntnisse. Inklusive elektronischer Steuererkl&auml;rung (ELSTER) mit digitaler Signatur.',10,26,1,'false',0.00),
('Paragon NTFS für Mac OS X 10',22.74,9,'Plattform&uuml;bergreifend mit Mac&reg; und Windows&reg; arbeiten - effektiv und schneller als je zuvor! Paragon NTFS f&uuml;r Mac OS X ist der einzige NTFS-Treiber, der lesend und schreibend genauso schnell auf das Windows NTFS-Dateisystem zugreifen kann wie auf native HFS+-Dateien. Plattform&uuml;bergreifend mit Mac und Windows arbeiten - effektiv und schneller als je zuvor! Paragon NTFS f&uuml;r Mac OS X ist der einzige NTFS-Treiber, der lesend und schreibend genauso schnell auf das Windows NTFS-Dateisystem zugreifen kann wie auf native HFS+-Dateien. NTFS f&uuml;r Mac OS X 10 unterst&uuml;tzt als erster NTFS-Treiber das Apple-Betriebssystem OS X 10.8 Mountain Lion!',10,27,15,'false',0.00),
('Corel Aftershot Pro',64.05,9,'Corel AfterShot Pro ist eine schnelle und flexible L&ouml;sung f&uuml;r den gesamten Fotoworkflow. Sie bietet professionelle Funktionen f&uuml;r die Verwaltung der Fotos, die Bildbearbeitung unter Beibehaltung der Originaldatei und die komplette Verarbeitung von RAW-Formaten. Ordnen und sortieren Sie Ihre Fotos mithilfe von Katalogen und Ordnern. Finden Sie sofort das gesuchte Foto dank umfassender Metadaten-Werkzeuge, die eine Suche anhand von Kameraeinstellungen, Schlagw&ouml;rtern, Markierungen und vielem mehr erm&ouml;glichen. Probieren Sie mit nichtdestruktiven Anpassungswerkzeugen beliebige &Auml;nderungen aus und wenden Sie Optimierungen mit selektiven Bearbeitungsfunktionen pr&auml;zise an. Probieren Sie mit nichtdestruktiven Anpassungswerkzeugen beliebige &Auml;nderungen aus. Leistungsstarke Stapelverarbeitungsfunktionen, vielf&auml;ltige Ausgabeoptionen und eine bahnbrechende Performance garantieren eine Beschleunigung des professionellen Fotoworkflows mit AfterShot Pro.',10,28,0,'false',0.00),
('Adobe Captivate dt. Win -Student/Teacher- v6',302.85,9,'Adobe Captivate 6 erm&ouml;glicht das schnelle Erstellen einer gro&szlig;en Auswahl von interaktiven E-Learning- und HTML5-basierten M-Learning-Inhalten. Erstellen Sie einfach Produktdemos in HD, Anwendungssimulationen sowie Materialien f&uuml;r Soft-Skill- und Compliance-Schulungen. Sie k&ouml;nnen Microsoft PowerPoint-Folien importieren und Inhalte mit Multimedia, interaktiven Elementen und Tests aufwerten. Fertige Inhalte k&ouml;nnen praktisch auf jedem Endger&auml;t, einschlie&szlig;lich iPads, bereitgestellt werden. Mit Adobe Captivate erstellen Sie im Handumdrehen professionelle E-Learning-Erlebnisse inkl. Software-Demos, Simulationen, Tests und vieler anderer interaktiver Inhalte. Programmier- oder Multimedia-Kenntnisse sind dabei nicht erforderlich. Steigern Sie Ihre Produktivit&auml;t mithilfe von Vorlagen und Funktionen f&uuml;r effektivere Teamarbeit. Captivate ist mit LMS-Systemen und Adobe Acrobat Connect Pro integrierbar, sodass Sie Inhalte praktisch &uuml;berall bereitstellen k&ouml;nnen.',10,29,2,'true',10.00),
('Adobe Acrobat XI v11 Std dt. Win (MediaKit)',36.95,10,'Egal ob Erstellung, Bearbeitung oder Unterzeichnung von PDF-Dokumenten Adobe&reg; Acrobat&reg; XI Standard macht Ihnen das Arbeitsleben leichter. Optimieren Sie Ihren Dokumenten-Workflow mit leistungsf&auml;higen Funktionen f&uuml;r effiziente Zusammenarbeit, die Zusammenstellung unterschiedlicher Inhalte zu &uuml;bersichtlichen Adobe PDF-Portfolios, die elektronische Abstimmung, die Erstellung und Verwaltung dynamischer Formulare sowie den Schutz vertraulicher Daten. Lizenztyp : Nur Datentr&auml;ger ohne Lizenz Sprache(n) : Deutsch Medium : DVD-ROM Adobe Acrobat XI Standard CLP/TLP Mediakit.',10,29,52,'true',0.00),
('Franzis PDF Editor Platin dt. Win',106.47,10,'Geschlossene PDF-Dokumente frei bearbeiten - mit dem PDF Editor platin bearbeiten Sie Dokumente und korrigieren Tippfehler direkt im PDF. Verschieben Sie komplette Seiten oder Textteile, &auml;ndern Sie die Reihenfolge der Seiten, f&uuml;gen Sie Grafiken ein oder passen Sie Bilder in Ausrichtung und Gr&ouml;&szlig;e an.',10,29,0,'false',0.00),
('Data Becker 3D TRAUMHAUS DESIGNER 11 PREM.',88.95,10,'GR',10,30,51,'false',5.00),
('Franzis Panorama Project 2.0 dt. Win',54.99,10,'Aus &uuml;berlappenden Einzelbildern erstellt Panorama Project 2 vollautomatisch eindrucksvolle 2D- oder 3DPanoramen. Die Einzelbilder werden mit unsichtbaren &Uuml;berg&auml;ngen zusammengef&uuml;gt und mit Hilfe der CPU- und GPUTechnologie in Sekundenschnelle erstellt. Nat&uuml;rlich haben Sie trotzdem die M&ouml;glichkeit, manuell einzugreifen und die Bild&uuml;berg&auml;nge anzupassen.',10,31,5,'false',0.00),
('Steinberg Cubase 7 EDU GBFIESPT',314.96,10,'Mit noch mehr musikalischen Tools als jemals zuvor, bietet Cubase 7 eine unvergleichlich kreative Produktionserfahrung. Das komplett &uuml;berarbeitete Mischpult, die neue Akkord-Spur, der innovative Chord Assistant, ein noch leistungsst&auml;rkeres VariAudio, mehr Sounds f&uuml;r Ihre Instrumente und viele weitere Optimierungen machen Cubase 7 zu einer noch m&auml;chtigeren L&ouml;sung f&uuml;r alle Bereiche der Musikproduktion.',10,32,0,'false',0.00),
('Netbook 10,1 Zoll (25,65cm) Asus EeePC X101CH-RED003U rot N2600-2x1,6GHz, 1GB, 320GB',224.55,11,'Der 17,6 Millimeter d&uuml;nne und mit 920 Gramm Gewicht federleichte 10,1 Z&ouml;ller mit mattem Display basiert erstmals auf dem Betriebssystem Intel MeeGo. Es wurde speziell entwickelt, um die Verbindung der Nutzer zu ihren Lieblingsseiten und sozialen Netzwerken besonders schnell und einfach aufzubauen. Damit sorgt der Eee PC f&uuml;r ein v&ouml;llig neues Social Networking Erlebnis. G&auml;ngige Unterhaltungs- und Social Networking-Anwendungen wie Facebook oder Twitter Apps sowie ein Instant Messaging Client sind vorinstalliert und lassen sich &uuml;ber einen einfachen Klick aufrufen.',10,7,55,'false',0.00),
('Netbook 11,6 Zoll (29,46cm) Lenovo IdeaPad S206 E1-1200-2x1,4Ghz, 4GB, 320GB, HD7310, W7HP',337.9,11,'Vorinstalliert mit Original Windows&reg; 7 Home Premium. Schlanker als ein Netbook und leichter als ein Notebook mit diesem eleganten mobilen PC ist deine Online-Welt nur einen Tastendruck entfernt.',10,33,0,'false',0.00),
('Netbook 10,1 Zoll (25,65cm) Asus EeePC X101CH-WHI003U Atom N2600-2x1,6GHz, 1GB, 320GB',223.65,11,'Der neue ASUS Eee PC X101CH ist eines der wenigen Netbooks, die auf der diesj&auml;hrigen Consumer Electronics Show (CES) zu sehen sind. Der X101CH ist das neue Einsteiger-Netbook von ASUS, das im Februar zu Preisen ab 269 Dollar auf den Markt kommen soll. Die Ausstattung rund um den neuen Intel Atom N2600 Dual Core Prozessor der &quot;Cedar Trail&quot;-Familie f&auml;llt dementsprechend grundlegend aus, verbaut ASUS doch lediglich einen 3-Zellen-Akku der h&ouml;chstens vier Stunden Laufzeit erm&ouml;glichen d&uuml;rfte sowie ein Display mit 1024&times;600 Pixeln.',10,7,58,'false',0.00),
('Netbook 11,6 Zoll (29,46cm) Hewlett Packard EliteBook 2170P I5-3427U 4GB 180GB SSD',1533.57,11,'Der ultimative Reisebegleiter von HP. Das &auml;u&szlig;erst kompakte und leichte HP EliteBook wurde speziell f&uuml;r Windows 7 Professional optimiert. Es hat ein HD-Display mit einer Diagonalen von 29,4 cm, ein sehr robustes Design, viele Anschlussm&ouml;glichkeiten und einen Niederspannungs-Prozessor.',10,34,78,'false',0.00),
('Netbook 10,1 Zoll (25,65cm) Asus EeePC X101CH-BLK006U Atom N2600-2x1,6GHz, 1GB, 320GB',223.65,11,'Der neue ASUS Eee PC X101CH ist eines der wenigen Netbooks, die auf der diesj&auml;hrigen Consumer Electronics Show (CES) zu sehen sind. Der X101CH ist das neue Einsteiger-Netbook von ASUS, das im Februar zu Preisen ab 269 Dollar auf den Markt kommen soll. Die Ausstattung rund um den neuen Intel Atom N2600 Dual Core Prozessor der &quot;Cedar Trail&quot;-Familie f&auml;llt dementsprechend grundlegend aus, verbaut ASUS doch lediglich einen 3-Zellen-Akku der h&ouml;chstens vier Stunden Laufzeit erm&ouml;glichen d&uuml;rfte sowie ein Display mit 1024&times;600 Pixeln.',10,7,0,'false',3.00),
('Notebook 14 Zoll (35,56cm) Dell Vostro 3460 6487 rot',628.46,12,'Setzen Sie Ihre Ideen um. Sichern Sie Ihre Daten.Dieses fortschrittliche 35,56 cm Notebook bietet wichtige Sicherheitsfunktionen und einen leistungsstarken Prozessor. L&uuml;ckenlose Sicherheit; extrem schneller System- und Anwendungsstart.',10,35,98,'true',0.00),
('Notebook 17,3 Zoll (43,94cm) Toshiba Satellite Pro C870-19N i3-3110M-2x2,4GHz, 4GB, 750GB',494.81,12,'Der Toshiba Satellite Pro C870 ist das perfekte Notebook f&uuml;r Business-Profis, die mehr &Uuml;berblick wollen - denn daf&uuml;r bietet das gro&szlig;e, entspiegelte LED-Display mit 43,9 cm die besten Voraussetzungen. Auch in Sachen Prozessoren und Anschl&uuml;sse ist der C870 auf dem modernen Stand. Ein idealer Mix aus Performance, Komfort und vern&uuml;nftigem Preis - genau das Richtige, um Ihr Unternehmen voranzubringen.',10,36,0,'true',0.00),
('Notebook 15,6 Zoll (39,62cm) Hewlett Packard 650 Pentium B970, 2GB RAM, 320GB, Linux',318.93,12,'Entscheidende Mobilit&auml;t. Dieses preisg&uuml;nstige Notebook bietet Intel-Technologie, Wireless-Funktionen und alle wesentlichen Multimedia Tools. Die robuste H&uuml;lle im edlen Design sch&uuml;tzt das attraktive Aussehen des Laptops. Intel Pentium B970, 2x 2.30GHz &bull; 2048MB &bull; 320GB &bull; DVD+/-RW DL &bull; Intel HD Graphics (IGP) shared memory &bull; 3x USB 2.0/Gb LAN/WLAN 802.11bgn &bull; HDMI &bull; 2in1 Card Reader &bull; Webcam &bull; 15.6&quot; WXGA non-glare LED TFT (1366x768) &bull; Linux &bull; Li-Ionen-Akku (6 Zellen)',10,34,46,'false',0.00),
('Notebook 13,3 Zoll (33,78cm) Asus Zenbook Prime UX31A-R4003H',1413.61,12,'Das Design verschmilzt bei dem aus Aluminium gefertigten ASUS ZENBOOK nahtlos mit Technologie. Mittig auf der stylischen Geh&auml;useoberfl&auml;che sind feine, konzentrische Kreise eingearbeitet, die das Licht brechen und so die Sinne stimulieren. Mit dem modernen Design ist die Silhouette des ASUS ZENBOOK extrem schmal - es ist das d&uuml;nne Ultrabook und spricht damit besonders ultramobile Anwender an.',10,7,0,'false',0.00),
('Notebook 15,6 Zoll (39,62cm) Samsung 700Z5C-S05 i7-3615QM-4x2,3GHz, 8GB, 1000GB, 16Gb SSD',1185.67,12,'39.6 cm (15.6 &quot;)/ 8 GB RAM (2x 4 GB)/ Windows 8 Professional 64-Bit/ Office 2010 Product Key Ready: Ja/ HD+ (1680 x 945 Pixel)/ NVIDIA GeForce GT 640M/ 1000 GB HDD/ SATA/ DVD-SuperMulti (DL)',10,37,6,'false',0.00),
('10.1 Zoll (25,65cm) Samsung Tab 2 10.1 3G/WiFi/Bluetooth V3.0 32GB weiss',418.96,13,'Vielf&auml;ltige Lesestoffquelle: Mit Readers Hub haben Sie Zugriff auf unz&auml;hlige Zeitschriften, Zeitungen und B&uuml;cher. Egal ob Sie nun im Supermarkt ein Rezept f&uuml;r ein gutes Essen suchen oder entspannt im Caf&eacute; oder Park sitzen: Anregender Lesestoff ist immer dabei.',10,37,4,'false',5.00),
('10.1 Zoll (25,65cm) Huawei MediaPad 10FHD WiFi/Bluetooth V3.0 8GB schwarz',358.96,13,'Noch nie dagewesenes Entertainment bietet das 8,8 mm-schlanke HUAWEI MediaPad 10FHD mit seinem 25,4 cm (10 Zoll)-IPS-Multi-Touch-Display bei einer Full-HD-Aufl&ouml;sung von 1920 x 1200 Pixeln. Der 1,2 GHz K3 Quad-Core-Prozessor sorgt gemeinsam mit den 1GB RAM-Arbeitsspeicher f&uuml;r unglaublich schnelle Rechenleistung - auch bei vielen parallel laufenden Programmen. Gestochen scharfe Bilder und Videos garantiert die r&uuml;ckseitige 8 Megapixel Autofokus-Kamera.',10,38,894,'false',0.00),
('8.0 Zoll (20,32cm) Intenso INTAB 8" WiFi 8GB schwarz',107.85,13,'Display: 20,32 (8&quot;) kapazitives Display mit Gravitationssensor Aufl&ouml;sung: 800 x 600 Pixel (max.) Betriebssystem: Android 2.3 CPU: 1 GHz (Cortex A8) Interner Speicher: 8 GB Arbeitsspeicher: 512 MB DDR3 W-LAN: WIFI 802. 11 b/g/n, Mobiles Internet.',10,39,4,'false',10.00),
('10.1 Zoll (25,65cm) Samsung Galaxy Note 10.1 N8000 3G/WiFi/Bluetooth V4.0 16GB schwarz/grau',521.09,13,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,37,0,'false',0.00),
('9.4 Zoll (23,88cm) Sony Tablet S WiFi/Bluetooth V3.0 16GB schwarz',364.00,13,'Genie&szlig;en Sie zu Hause, unterwegs oder im Urlaub beeindruckend schnelle Apps, Spiele, Internet, Videos und Musik mit dem bisher wohl beeindruckendsten Xperia&trade; Erlebnis. Ein Platz f&uuml;r Ihren Alltag - Dank seines superflachen Aluminiumgeh&auml;uses und spritzwassergesch&uuml;tzten Bildschirms k&ouml;nnen Sie ohne Bedenken mit nassen H&auml;nden Rezepte aufrufen und es ins Freie mitnehmen. Es ist jederzeit und &uuml;berall einsatzbereit.',10,40,464,'false',0.00),
('ASRock VISION 3D 137B/B Bulk',578.86,14,'Coretrade; i3-370M Mobile Prozessor NVIDIA GeForce GT 425M 500 GB 4096 MB',10,11,6,'false',0.00),
('ASUS EeeTOP ET2012AUTB-B020A schwarz',466.49,14,'Einfach zu installieren und zu benutzen. Einfach auspacken, aufstellen, anschlie&szlig;en, und arbeiten. Das platzsparende Design schafft Freiraum auf dem Schreibtisch und gew&auml;hrleistet unkompliziertes Arbeiten. Die Schrauben der Wandhalterung bieten eine zus&auml;tzliche M&ouml;glichkeit, den Arbeitsplatz effizienter zu nutzen.',10,7,84,'true',0.00),
('Zotac ZBOX ID83 BE Intel Core i3-3120M',319.47,14,'Intel HM76 Chipsatz, Intel Core i3-3120M CPU, Intel HD 4000 Graphics, 2x DDR3 1600 SODIMM RAM-Slots (bis zu 16GB), 1x 2,5&quot; HDD/SSD SATA 6.0 Gb/s Slot , 802.11n WIFI, Gigabit LAN, Bluetooth 4.0, USB 3.0, USB 2.0, HDMI, DVI, SPDIF, 6-1 Cardreader, Windows 8 ready',10,10,854,'true',0.00),
('Shuttle XPC XS 3601BA USFF schwarz',453.75,14,'Der Mini PC von Shuttle ist ausgestattet mit Intel Atom D2500 Dual-Core Prozessor, 2GB Arbeitsspeicher, 320GB Festplatte und Windows 7 Professional. XS 3601BA ist ein extrem schlanker Slim-PC mit &auml;u&szlig;erst &ouml;kologischen und ergonomischen Ambitionen. Denn sein Stromverbrauch ist fast nicht der Rede wert und durch den Verzicht auf jegliche L&uuml;fter ist es wartungsarm und fast ger&auml;uschlos.',10,41,4,'false',0.00),
('15,6 Zoll (39,62cm) Shuttle X50V3 Touch-AIO/Intel Atom 2,13GHz/weiß 40W',350.47,14,'Das Shuttle X50 Barebone ist mit einem 39,6 cm gro&szlig;en Touchscreen und dem stromsparenden Prozessor ausgestattet. Per Gigabit-LAN und WLAN ist das X50 stets gut vernetzt. Webcam, Mikrofon und integrierte Stereo-Lautsprecher runden das Bild des multimedialen Vielseiters ab. Sie entscheiden wie viel Speicher, welche 6,35-cm-Festplatte/SSD und welches Betriebssystem Ihren All-in-One-PC vervollst&auml;ndigt. Der Zusammenbau stellt f&uuml;r hardwarekundige Anwender keine gro&szlig;en Schwierigkeiten dar. All-in-one Touchscreen-Barebone von Shuttle wei&szlig; Display: 39,62 cm(15,6&quot;) resistiver Touchscreen (1366x768) CPU: Intel ATOM D2700 Dual Core 2,13 GHz Chipsatz: Intel NM10 Express Chipsatz Speicher: Unterst&uuml;tzt DDR3-800/1066 (oder h&ouml;her) ',10,41,884,'false',0.00),
('Dell Inspiron One 2330 5475 SKU24',878.02,15,'Interaktion und Unterhaltung mit dem neuen Inspiron&trade; One 23 All-in-One. Er ist mit einem 23-Zoll-Touchscreen (58,4 cm) und Intel&reg; Core&trade; Prozessoren bis hin zur dritten Generation ausgestattet.',10,35,4,'false',30.00),
('Intel "Box Canyon" DC3217BY',278.98,15,'Nur 116,6 x 112,0 x 39,0 mm gro&szlig; passt die Intel Box praktisch &uuml;berall hin. Sie bietet Platz f&uuml;r ein mSATA Laufwerk. Antennen f&uuml;r WiFi und Bluetooth sind voreingebaut, ebenso Front Panel USB 2.0. QS77 Express Chipsatz, intel Core i3-3217U Prozessor (HD4000 Grafik), 1x HDMI 1.4a, 1x Thunderbolt, 3x USB2.0 (davon 1x Front), 2x SO-DIMM Sockel f&uuml;r bis zu 16GB, 2x mini-PCIe (1x full-length mit mSATA Support, 1x half-length), Masse Ger&auml;t ca. : 117mm x 112.0mm x 39.0mm, VESA Befestigung, Netzteil inklusive, Netzkabel muss separat erworben werden.',10,13,97,'false',0.00),
('Shuttle XPC-SH67H3 S1155 H67 MATX 300W',247.96,15,'Seinem Ruf als Pionier im Mini-PC-Bereich folgend, ver&ouml;ffentlicht Shuttle nun auch ein innovatives XPC Barebone f&uuml;r Intels aktuellste &quot;Sandy Bridge&quot;-Plattform. Das SH67H3 unterst&uuml;tzt alle Intel Core i3 / i5 / i7 Prozessoren mit Sockel 1155 und bis zu 16 GB DDR3-Speicher, verteilt auf vier Steckpl&auml;tze. Der PCIe-x16-Steckplatz des SH67H3 nimmt auch gro&szlig;e Dual-Slot-Grafikkarten auf. Alternativ kann die in geeigneten CPUs integrierte Grafikfunktion genutzt werden. Mit HDMI und DVI stehen erstmals gleich zwei digitale Monitoranschl&uuml;sse zur Verf&uuml;gung. An Anschl&uuml;ssen wurde allgemein nicht gespart: 4x USB 3.0, 4x USB 2.0, 2x eSATA, 1x COM und S/PDIF sind auf Front- und R&uuml;ckseite verteilt. Abgerundet wird das attraktive Paket aus Aluminium mit Gigabit-LAN und einem effektiven Heatpipe-K&uuml;hlsystem.',10,41,4,'false',0.00),
('ZOTAC Barebone ZBox AD11 Nano XS (AMD E-450,HD6320,DDR3)',218.67,15,'Die ZOTAC&reg; ZBOX nano XS AD11 ist der wohl weltweit kleinste PC mit einer starke High-Definition Desktop-Performance. Die AMD E-450 APU mit Radeon&trade; HD 6320 Grafik bildet dabei das Herzst&uuml;ck der ZBOX nano XS AD11 und liefert zum einen enorme Multi-Tasking-F&auml;higkeiten und zum anderen eine beeindruckende Grafikperformance mit DirectX&reg; 11 Unterst&uuml;tzung sowie Full-HD Videowiedergabe in kristallklaren 1080p.',10,10,1,'false',20.00),
('Sapphire Mini PC Edge VS4 (EU) AMD A4',263.2,15,'Eigentlich kennt man Sapphire haupts&auml;chlich von Grafikkarten. Doch vor kurzem hat Sapphire sein portfolio erweitert. Sowohl der Edge VS 4, als auch der Edge VS 8 setzten auf einen Trinity-Prozessor. Beim VS 4 kommt eine A4-4335M-APU zum Einsatz. Die zwei Kerne takten mit jeweils 1,9 GHz - dar&uuml;ber hinaus bietet die APU als integrierte Grafikeinheit eine Radeon HD 7400G. Als Chipsatz kommt bei beiden Mini-PCs der A70M von AMD zum Einsatz. Ebenso in beiden Modellen sind jeweils vier-GiByte-DDR3-1333 verbaut. Zum Speichern von Daten stehen Ihnen beim VS 4 320 GiByte Festplattenspeicher zur Verf&uuml;gung.',10,42,47,'false',0.00),
('Audioline Amplicom AB 900',30.86,16,'Wiedergabegeschwindigkeit ohne Verzerrungen erh&ouml;hen oder verringern Verst&auml;rkertaste (Boost) f&uuml;r besonders laute Wiedergabe (+40 dB) entweder &uuml;ber den Lautsprecher oder &uuml;ber das Headset Digitale Lautst&auml;rkeregelung Klangfarbe f&uuml;r Wiedergabe einstellbar 3,5 mm Headset (Kopfh&ouml;rer) - Anschluss Ca. 25 Minuten Aufzeichnungskapazit&auml;t 2-stelliges Display als Nachrichtenz&auml;hler Digitale Aufzeichnung der Ansage und eingehender Nachricht Maximale Begr&uuml;&szlig;ungsl&auml;nge: 60 Sekunden Maximale Nachrichtenl&auml;nge: 120 Sekunden Nachrichten &uuml;berspringen, wiederholen, l&ouml;schen, unterbrechen Ansage von aktuellem Datum und aktueller Uhrzeit Anrufbeantworter Ein/Aus 6 Sprachen einstellbar (DE, EN, FR, IT, ES, NL) Voreingestellter Begr&uuml;&szlig;ungstext (&auml;nderbar) Tages- und Uhrzeitansage bei Nachrichtenwiedergabe Automatisches Speichern Anzeige: Speicher voll Gespr&auml;chsannahme nach 2 oder 6x klingeln Geb&uuml;hrensparfunktion f&uuml;r Fernabfrage Mith&ouml;rfunktion bei eingehenden Nachrichten Fernbedienbar mit Sicherheitscode.',10,43,51,'false',0.00),
('Tiptel 540 SD AB Anrufbeantworter',165.81,16,'Der Profi-Anrufbeantworter tiptel 540 office ist ideal geeignet f&uuml;r jedes B&uuml;ro und f&uuml;r anspruchsvolle private Nutzer. Dank seiner hochwertigen Flash-Memory-Technologie werden Ansagen und Aufzeichnungen so klar und deutlich wiedergegeben.',10,44,74,'false',0.00),
('Audioline AB871 Silber Anrufbeantworter',14.97,16,'Digitaler Anrufbeantworter, bis zu 30 Minuten Aufzeichnungszeit, Ansagetexte: 1, Mith&ouml;rm&ouml;glichkeit, Wochentag-/Uhrzeitsteuerung',10,43,0,'true',0.00),
('Telekom Concept A412 AB schwarzblau',20.45,16,'Die Deutsche Telekom ist Europas gr&ouml;&szlig;tes Telekommunikationsunternehmen und einer der weltweiten Innovationsmotoren ihrer Branche. Die Produkte und Services von Deutsche Telekom setzen nicht nur in Deutschland, sondern vielfach auch weltweit Ma&szlig;st&auml;be. Das Unternehmen sorgt daf&uuml;r, dass seinen Kunden - egal, ob Festnetz-Telefon, Handy, Internet oder Gesch&auml;ftskundenl&ouml;sung - immer state-of-the-art-L&ouml;sungen zur Verf&uuml;gung stehen und sie so als erste von den faszinierenden Perspektiven und M&ouml;glichkeiten der Informationsgesellschaft profitieren. LEISTUNGSMERKMALE: Digitale Sprachspeicherung (20 Min.); 14-stelliges LED-Display; Abfrage der Anrufe f&uuml;r Blinde mit markierter Taste; Mith&ouml;ren, Fernabfrage; Memory-Speicher, auch bei Stromausfall Erhalt der Nachrichten; Aufzeichnungszeit pro Anruf max. 180 Sekunden.',10,45,0,'true',0.00),
('Doro Comfort 3005',38.21,16,'Doro Comfort 3005 mit integriertem Anrufbeantworter bietet h&ouml;chste Funktionalit&auml;t verbunden mit Bedienerfreundlichkeit, Komfort und der M&ouml;glichkeit, bei Bedarf die Lautst&auml;rke f&uuml;r H&ouml;rer, Lautsprecher oder Anrufton zu erh&ouml;hen. Doro Comfort 3005 ist ein einfach zu bedienendes schnurgebundenes Telefon mit Anrufbeantworter. Doro Comfort 3005 mit integriertem Anrufbeantworter bietet h&ouml;chste Funktionalit&auml;t verbunden mit Bedienerfreundlichkeit, Komfort und der M&ouml;glichkeit, bei Bedarf die Lautst&auml;rke f&uuml;r H&ouml;rer, Lautsprecher oder Anrufton zu erh&ouml;hen.',10,46,0,'false',0.00),
('Gigaset C300A schwarz',52.70,17,'ECO DECT Telefon, 1,7&quot; 128x128 Pixel, gro&szlig;es Farb-Display mit 4 Farbschemas zur Auswahl, Hochwertige beleuchtete Tastatur &quot;Metaldom-Technologie&quot;, R-Taste, 250 Telefonbuchspeicher mit VIP-Ruf &quot;Farbeschemas&quot;, 30er Anruferliste, Freisprechen im Mobilteil.',10,47,54,'false',0.00),
('Gigaset DX600A ISDN titanium',169.03,17,'ISDN-Telefon, strahlungsarm, schnurgebunden, integrierter Anrufbeantworter, DECT, GAP-kompatibel, Display: farbig, beleuchtet, Telefonbuchfunktion, bis 750 Nummernspeicher, Anruferliste, CLIP-Funktion, Foto/Rufnummernzuordnung, Freisprecheinrichtung, SMS-Funktion.',10,47,4,'false',0.00),
('T-COM Concept PX 722 ISDN Systemtelefon Schwarzblau',123.69,17,'Das neue T-Concept PX722 ist das aktuelle Komfort-Systemtelefon f&uuml;r die T-Concept Telefonanlagen XI721, XI521 und XI524 DSL. Der komplette Funktionsumfang der Telefonanlagen wird von diesem Ger&auml;t voll unterst&uuml;tzt. Die Konfiguration des T-Concept PX722 kann bequem &uuml;ber die angeschlossene Telefonanlage vorgenommen werden. Die Men&uuml;f&uuml;hrung des Komforttelefons selbst wird mit zehn Funktionstasten bedient. Per Tastendruck kann auch auf das Telefonbuch der angeschlossenen Telefonanlage zugegriffen werden.',10,45,54,'false',0.00),
('Doro MemoryPlus 319iph',54.52,17,'Besonders hilfreich f&uuml;r Menschen mit eingeschr&auml;nkter Fingermotorik oder Einschr&auml;nkungen beim Ged&auml;chtnis dank ergonomischer Tastatur, FotoDirektwahltasten und H&ouml;rer sowie eine sichere H&ouml;rerablage. Auch f&uuml;r h&ouml;rbeeintr&auml;chtigte bis schwerh&ouml;rige Menschen gut geeignet.',10,46,0,'false',10.00),
('Gigaset SX810 A ISDN stahlgrau',151.85,17,'Gigaset Siemens SX810A ISDN - ISDN-Schnurlostelefon mit integrierter Bluetooth-Schnittstelle, Anrufbeantworter und Anruferkennung - DECTGAP - Stahlgrau',10,47,0,'false',0.00),
('LG Electronics Optimus 4X P880 True HD weiß',322.86,18,'Ein m&auml;chtiger Stern erstrahlt am Smartphone-Himmel: das LG Optimus 4X HD - nichts weniger als ein Multimedia-Wunderwerk. Die 1,5-GHz-Quad-Core-Performance und der NVIDIA GeForce-Grafikchip bringen das beeindruckende 11,9 cm gro&szlig;e True HD-IPS-Display regelrecht zum Gl&uuml;hen - mit brillanter HD-Action f&uuml;r Android-Games in Konsolenqualit&auml;t und satter Leistung f&uuml;r jede erdenkliche Anwendung. Dar&uuml;ber hinaus ist das Smartphone mit reichlich Ausdauer gesegnet - dank kraftvollen Akkus, sparsamer IPS-Display-Technologie und eines zus&auml;tzlichen f&uuml;nften Energiespar-Kerns f&uuml;r Basisaufgaben und aktiven Stand-by. Kompromisslos elegantes Design und eine 8-Megapixel-Kamera runden das Bild souver&auml;n ab. Zudem bieten clevere Features wie die Quick Memo-Funktion - f&uuml;r schnelle Screenshots zum Beschriften und zum Teilen - mehr Spontanit&auml;t auf Tastendruck. LG Optimus 4X HD - ganz einfach das ultimative Entertainment-Smartphone.',10,48,646,'false',0.00),
('Sony Xperia U schwarz/weiß',148.66,18,'Jetzt kannst du jeden Ausschnitt aus jedem Film oder Video in kristallklarer Qualit&auml;t ansehen. Die fantastische Stimmung auf der Party im letzten Jahr l&auml;sst sich in super Aufl&ouml;sung bis ins Detail erneut aufleben. Auf dem 8,89-cm-Touchscreen Reality mit Mobile BRAVIA Engine wird echte Magie zur Realit&auml;t. &Uuml;ber die vorinstallierte Anwendung Video Unlimited von Sony Entertainment Network kannst du bequem nach den neuesten Hollywood-Blockbusters suchen.',10,40,0,'false',0.00),
('Samsung Galaxy S3 Mini I8190 8GB schwarz',265.12,18,'Dual Core/ Android/ 10,16 cm (4&quot;)/ Aufl&ouml;sung: 800 x 480 Pixel/ EDGE, HSUPA, UMTS, GPRS/ schwarz/ 122 x 63 x 9,9 mm mm/ 120/ Micro-SD',10,37,64,'false',0.00),
('Samsung Ativ S I8750 silber',406.00,18,'Das Samsung ATIV S, gestaltet mit elegant-strichgeschliffener Oberfl&auml;che, verspricht starke Leistung kombiniert mit einer gro&szlig;z&uuml;gigen Auswahl an Content-Sharing Optionen und sinnvollen Funktionen. Die neuesten Versionen von MS Word, PPT, Excel und OneNote sind vorinstalliert, damit Sie die besten Pr&auml;sentationen erstellen, Dokumente jederzeit bearbeiten, auf SkyDrive zum Sichern, Speichern oder Teilen hochladen k&ouml;nnen.',10,37,64,'true',0.00),
('Nokia Lumia 820 rot',453.52,18,'Mit Smart Shoot wird mit einem Tastendruck gleich eine ganze Serie von Fotos aufgenommen. Diese k&ouml;nnen dann zu einem Foto kombiniert werden, damit jede Person optimal aufs Bild kommt. Mit offenen Augen und einem L&auml;cheln die perfekte Aufnahme eben. Sie suchen ein Restaurant oder haben Lust auf einen Drink? Nokia City-Kompass zeigt Ihnen Gesch&auml;fte, Restaurants und Unternehmen in der Umgebung. Sie k&ouml;nnen Kritiken lesen, einen Tisch reservieren und den schnellsten Weg zum Restaurant finden. W&auml;hlen Sie f&uuml;r Ihr Nokia Lumia 820 ein Ladecover mit kabelloser Ladefunktion, und Sie k&ouml;nnen auf Kabel verzichten. Sie brauchen das Cover nur auf eine Ladeplatte oder das Nokia Ladekissen by Fatboy zu legen, um den Akku aufzuladen.',10,49,0,'true',0.00),
('Blaupunkt New York 800',898.95,19,'Blaupunkt New York 800 - Navigationssystem mit DVD Player, LCD Monitor, Digital Player und Radio.',10,50,64,'false',0.00),
('Garmin dezl 760 LMT-D',438.67,19,'Der neue dezl 760LMT-D mit 7 Zoll XXL Display stellt sich jeder Herausforderung, die der Alltag eines LKW-Fahrers mit sich bringt! Sicher ankommen mit spezifischen Routings und Parametern (Breite, H&ouml;he, Gewicht, Achslast, Art der Ladung) f&uuml;r LKWs und Wohnmobile. Einfach &uuml;ber das Smartphone ins Internet und mit LIVE Ready Echtzeit-Verkehrsinformationen und Services abrufen. Zeigt spezifisch Gefahrenstellen und besondere Situation vorausschauend auf der Karte an um immer den &Uuml;berblick zu behalten.',10,51,0,'false',0.00),
('TomTom EU Traffic VIA 125',156.83,19,'Mit dem TomTom Via haben Sie das Steuer fest in der Hand. Navigation ist damit ein Kinderspiel. Der TomTom Via l&auml;sst sich per Sprachsteuerung bedienen. Praktisch, wenn Sie Adressen eingeben oder &uuml;ber die Freisprechanlage telefonieren. Mit dem cleveren Fahrspurassistenten meistern Sie die un&uuml;bersichtlichsten Kreuzungen. Und dank pr&auml;ziser Karten und IQ Routes bekommen Sie genaue Ankunftszeiten. Sprechen ist der einfachste und schnellste Weg, Ihr Ger&auml;t zu bedienen! Mit der Sprachsteuerung und der Adresseingabe per Spracherkennung navigieren Sie ohne die H&auml;nde vom Lenkrad zu nehmen und den Blick von der Stra&szlig;e abzuwenden. Nutzen Sie Ihr Ger&auml;t als Freisprecheinrichtung f&uuml;r Ihr Handy. Ab sofort k&ouml;nnen Sie beim Autofahren sicher telefonieren - so bleiben Sie flexibel und stets in Verbindung. Video abspielen Die praktische, ausklappbare Halterung ist in das Ger&auml;t integriert und somit immer da, wenn Sie sie brauchen. Die Halterung l&auml;sst sich sehr einfach an der Frontscheibe befestigen. Und bei Verwendung der optionalen Befestigungsscheibe k&ouml;nnen Sie das Ger&auml;t auch kopf&uuml;ber auf dem Armaturenbrett anbringen - der Bildschirminhalt dreht sich automatisch mit. Sie k&ouml;nnen gleich losfahren und haben die besten Karten zur Verf&uuml;gung. Dank der Geschwindigkeitsprofile von IQ Routes erhalten Sie die schnellste Route zu jeder Tageszeit. Zudem k&ouml;nnen Sie durch umfassende POI-Daten wie Telefonnummern und &Ouml;ffnungszeiten jetzt sogar noch mehr Informationen abrufen.',10,52,79,'false',3.00),
('Blaupunkt TravelPilot 40EUR Europa',133.72,19,'Exklusives Designgeh&auml;use mit Echt-Aluminium-Elementen.',10,50,69,'false',0.00),
('Garmin nüvi 3490LMT',250.46,19,'Mobiles Navigationsger&auml;t, f&uuml;r Autonavigation, 10,90 cm Bildschirm, 4,30 Zoll Diagonale, 16:9 Format, Touch-Screen Bedienung, Fahrspurassistent, Freisprecheinrichtung, Geschwindigkeitsassistent, Spracherkennung, TMC, Bluetooth, Li-Ionen-Akku.',10,51,0,'false',0.00),
('Linksys by Cisco 1 LINE IP PHONE,BW-DISPLAY',469.95,20,'SMALL BUSINESS IP PHONE',10,53,0,'false',0.00),
('Auerswald COMfortel 3500 schwarz Systemtelefon',401.31,20,'Welcher technische Standard wird sich durchsetzen? Kann eine Telefonanlage morgen schon veraltet sein? Solche Fragen r&auml;umt das COMfortel 3500 aus dem Weg - mit kompromissloser Vielseitigkeit! So vereint es erstmals Standard-SIP- mit IP-Systemtelefonie, d. h. es fungiert sowohl als Systemtelefon an einer Auerswald Telefonanlage als auch als Standard-SIP-Telefon an einer Soft-PBX oder einer IP-Centrex-L&ouml;sung eines Providers. Zudem l&auml;sst es sich sowohl per Tasten als auch &uuml;ber das gro&szlig;e Touch-Display bedienen und treibt das Komfort-Niveau damit in ungeahnte H&ouml;hen: Da das COMfortel 3500 auf dem bekannten Betriebssystem Android 2.3 basiert, l&auml;sst es sich nicht nur so komfortabel wie ein Smartphone bedienen, sondern auch ganz einfach Ihren pers&ouml;nlichen Anforderungen anpassen. Ganz nach Belieben k&ouml;nnen Sie zus&auml;tzliche Apps draufladen - ob Social Media wie Facebook und Twitter oder eine anspruchsvolle Eigenentwicklung, z. B. zur Steuerung einer TK-Anlage. Zus&auml;tzlich zur Tasten- und Touch-Steuerung erh&ouml;ht ein N&auml;herungssensor den Bedienkomfort, der z. B. das Klingeln durch eine knappe Handbewegung abschaltet, wenn es gerade st&ouml;rt. Um Ihre Kontaktdaten - ob unterwegs oder im B&uuml;ro - immer auf dem gleichen, aktuellen Stand zu halten, gleicht das COMfortel 3500 routinem&auml;&szlig;ig die Eintr&auml;ge mit denen auf Ihrem Handy ab und synchronisiert z. B. die Daten Ihres Outlook-Accounts, von Google -Diensten oder der TelekomCloud. &Uuml;brigens: Einmal mit Ihrem Handy gekoppelt, registriert das COMfortel 3500 per Bluetooth automatisch, ob Sie in der N&auml;he Ihres Telefons sind. Wenn nicht, wird der Ruf automatisch auf Ihr Handy geleitet. Auch der integrierte Anrufbeantworter gl&auml;nzt mit h&ouml;chstem Komfort: Er erkennt selbstt&auml;tig, ob es sich um einen internen oder externen Anruf, einen anonymen Anruf oder ein T&uuml;rsignal handelt - und reagiert entsprechend differenziert. Zus&auml;tzlich kann f&uuml;r jeden hinterlegten Kontakt eine spezielle Rufannahme hinterlegt werden. Dank integriertem VPN-Client k&ouml;nnen Verbindungen von Nebenstellen, wie z. B. einem Home-Office, zum Firmennetz so sicher hergestellt werden, wie dies sonst nur mit einem zus&auml;tzlichen VPN-Router m&ouml;glich ist. Durch die Tastenerweiterungsmodule COMfortel Xtension300 kann der Funktionsumfang betr&auml;chtlich erweitert werden: In der maximalen Ausbaustufe lassen sich bis zu 210 Funktionen bequem vom Telefon aus bedienen. Mit dem Set-up-Assistenten schlie&szlig;lich wird die Installation zum Kinderspiel. Das Telefon sucht nach dem Anschlie&szlig;en automatisch nach nach einem DHCP-Server bzw. einer Auerswald Telefonanlage, um sich anzumelden.',10,54,9,'false',0.00),
('Cisco UNIFIED PHONE 8945 Phantom Grey',316.31,20,'Cisco Unified Phone 8945, Phantom Grey, Slimline Handset',10,55,7,'false',0.00),
('Alcatel Temporis IP200 SIP PoE schwarz',62.27,20,'F&uuml;r diesen Artikel ist noch keine Produktbeschreibung vorhanden.',10,56,4897,'false',0.00),
('LG Electronics IP-Sys-Telefon Gigabit 3-line LCD',219.36,20,'LG Gigabit IP-Systemtelefon mit 3-zeiligem LCD-Display und 12 frei programmierbaren Tasten. Au&szlig;erdem verf&uuml;gt das Telefon &uuml;ber Freisprechfunktion und Anruferkennung.',10,48,0,'true',0.00),
('Sony DSC-WX80 (red) WiFi - Digitalkamera',168.94,21,'Halten Sie stimmungsvolle Momente rauschender Feste oder von Familientreffen und Urlaubstrips mit Sony DSC-WX80 fest. Detailreiche Fotos und flie&szlig;ende, stabile Full HD-Videos. Holen Sie entfernte Motive mit optischem 8fach-Zoom n&auml;her heran. Dann laden Sie die Aufnahmen einfach mithilfe des Kamera-Wi-Fi und Ihrem Telefon ins Internet hoch.',10,40,67,'true',4.00),
('Canon Ixus 125 HS blau',160.34,21,'Die IXUS 125 HS &uuml;berzeugt mit einem schlanken Metallgeh&auml;use im schicken Design und vielen n&uuml;tzlichen Funktionen - f&uuml;r gro&szlig;artige Bilder selbst bei wenig Licht. Face ID und Full-HD-Movies f&uuml;r noch mehr Filmspa&szlig;. Die IXUS 125 HS hat ein edles, schlankes Metallgeh&auml;use und passt in praktisch jede Jackentasche. Das 24-mm-Ultraweitwinkelobjektiv ist geradezu pr&auml;destiniert f&uuml;r Aufnahmen gro&szlig;er Personengruppen oder Landschaftspanoramen; mit dem 5fach optischen Zoom (bis zu 10fach mit ZoomPlus) holen Sie weit entfernte Motive nah heran. Das HS System brilliert bei schwachen Lichtverh&auml;ltnissen - ideal, um den Zauber einer Stimmung auch ohne Blitz und Stativ festzuhalten. Der fortschrittliche Digic 5 Prozessor und der hoch empfindliche 16,1 Megapixel starke CMOS-Sensor sorgen gemeinsam f&uuml;r &uuml;berzeugende Bildqualit&auml;t in allen Situationen. Intelligent IS mit sieben Modi passt den optischen Bildstabilisator automatisch an das Motiv an - durch Reduzieren von Verwacklungsunsch&auml;rfe entstehen gestochen scharfe, detaillierte Bilder und Videos selbst bei maximaler Zoomeinstellung und wenig Licht. Das gro&szlig;e, hochwertige LC-Display mit ca. 460.000 Bildpunkten erm&ouml;glicht die bequeme Men&uuml;navigation sowie eine komfortable Bildkomposition und -&uuml;berpr&uuml;fung aus nahezu jedem Winkel. Die speziell geh&auml;rtete Glasschicht sorgt f&uuml;r eine robuste Oberfl&auml;che. Die IXUS 125 HS kann mehr als nur fotografieren: Im Movie-Modus gelingen hervorragende Full-HD-Movies (1080p) mit 24 B/s und Stereoton; auch hier steht der optische Zoom zur Verf&uuml;gung. Intelligent IS reduziert Verwacklungsunsch&auml;rfe, selbst bei maximaler Zoomeinstellung. Die HDMI -Schnittstelle erlaubt den Anschluss an einen kompatiblen HD-Fernseher f&uuml;r die Wiedergabe in Topqualit&auml;t. Im intelligenten Automatik-Modus (Smart Auto) entstehen ganz komfortabel hochwertige Fotos oder Movies. 58 Aufnahmesituationen (21 bei Movies) werden unterschieden und automatisch die richtigen Einstellungen ausgew&auml;hlt. Smart Auto funktioniert auch bei Gesichtern im Motiv - dank Face ID erfolgt eine Anpassung der Aufnahmeeinstellungen an das Alter der Person. So werden etwa bei einem schlafenden Baby Blitz und Kamerager&auml;usche deaktiviert. Mit Face ID k&ouml;nnen Sie bis zu 12 Gesichter von Personen aus dem Familien- oder Freundeskreis registrieren - diese Gesichter genie&szlig;en bei der Scharfstellung automatisch Priorit&auml;t; au&szlig;erdem werden die Bilder mit den Namen versehen, damit man sie bei der Wiedergabe leicht wiederfindet. Ganz wie Sie wollen: Per High-Speed-Reihenaufnahmen erfassen Sie rasante Non-Stop-Action, und mit Super Slow Motion Movie lassen sich schnelle Bewegungen verlangsamt darstellen. Im Modus Nachtaufnahme ohne Stativ kombiniert die Kamera eine schnelle Folge von Einzelbildern zu einem Bild; so gelingen auch ohne Stativ gro&szlig;artige Bilder bei Nacht. Im Modus Filmtagebuch wird vor jedem Foto eine 4 Sekunden lange Moviesequenz aufgenommen; die Movieclips eines Tages k&ouml;nnen zu einem interessanten Bonus-Video in HD-Qualit&auml;t (720p) zusammengef&uuml;gt werden. Das optional als Zubeh&ouml;r erh&auml;ltliche Unterwassergeh&auml;use sch&uuml;tzt Ihre Kamera beim Outdoor-Einsatz und Unterwasseraufnahmen bis 3 m Tiefe.',10,57,494,'false',0.00),
('Nikon 1 J2 Kit inklusive NIKKOR VR 11-27,5 mm Systemkamera orange',358.25,21,'Der extrem schnelle Hybrid-Autofokus sorgt f&uuml;r eine besonders pr&auml;zise Fokussierung. So k&ouml;nnen Sie unter anderem schnelle Serien scharfer Fotos aufnehmen. Bei permanenter Autofokussierung sind bis zu 10 Bilder pro Sekunde m&ouml;glich. Dadurch werden selbst Motive in schneller Bewegung gestochen scharf dargestellt. Ist der Fokus voreingestellt, macht die Nikon 1 J2 bis zu 60 Bilder pro Sekunde. Das macht die Nikon 1 J2 zu einer Kamera, mit der Sie nie wieder einmalige Momente verpassen. Dabei ist Ihnen auf Wunsch auch der &quot;Smart Photo Selector&quot; behilflich. In diesem Modus nimmt die Kamera vor und nach dem Ausl&ouml;sen die ersten, scharfen Bilder auf und schl&auml;gt daraus die besten Aufnahmen vor.',10,58,974,'false',0.00),
('Casio Exilim Zoom EX-Z790 schwarz',109.48,21,'Fotospa&szlig; im gro&szlig;en Format - Casio EXILIM EX-Z790! 20,1 MP, 6fach opt. Zoom, Weitwinkeloptik ab 26 mm (entspr. Kleinbild), 6,9 cm TFT-Farbdisplay, Premium Auto, Selbstportrait, Gesichtserkennung, Easy Mode etc.',10,59,0,'false',0.00),
('Olympus PEN E-PM2 Kit inklusive EZ-M1442 II R Systemkamera schwarz',623.33,21,'Beste Bildqualit&auml;t ihrer Klasse - Olympus E-PM2! Mit dieser Kamera gelingen ihnen Profi-Fotos und dabei ist sie nicht einmal halb so gro&szlig; und schwer wie eine Profi-Kamera. Weiterhin: Fokussieren und ausl&ouml;sen mithilfe des Touchscreens, 12 Art Filter etc.',10,60,94,'false',1.00),
('Sony BDP-S 1100 BluRayPlayer schwarz',73.88,22,'Erh&ouml;hen Sie den Filmgenuss durch kristallklares Full HD und reinste Farben. Entdecken Sie klassische Szenen ihrer Lieblings-DVD neu. Verfolgen Sie jeden Moment einer Liebesgeschichte, einer dramatischen Verfolgungsjagd oder einer Comedyshow der neuesten Blu-ray&trade; Filme mit einem Gef&uuml;hl wie im Kino. Entdecken Sie mit Triluminos Colour die neuen Tiefen Ihrer Blu-ray Disc&trade; und DVD-Sammlung. Lehnen Sie sich zur&uuml;ck, und sehen Sie sich einen Film auf einem Triluminos-Fernseher an. Erleben Sie von staubigen D&uuml;nen eines Westerns bis hin zu einem d&uuml;steren, dunklen Sci-Fi-Thriller satte Farben, die der Geschichte echte Tiefe verleihen.',10,40,0,'false',0.00),
('Philips 3D Blu-ray Player, USB, DivX Plus HD BDP3380/12',102.12,22,'Entdecken Sie Film- und Musikgenuss in 3D. Erleben Sie mit Blu-ray und DivX Plus HD auf diesem schlanken Philips Blu-ray DVD-Player BDP3380 die magische Welt der Filme in Full HD. Genie&szlig;en Sie Ihre Lieblingsvideos und -musik direkt von USB-Flash-Laufwerken oder externen Festplatten mit USB 2.0 Media Link.',10,61,0,'false',0.00),
('Samsung BD-ES5000/EN',100.64,22,'Samsung BD-ES5000 - Blu-ray-Disk-Player - Hochskalierung - Ethernet',10,37,94,'false',0.00),
('LG Electronics Blu-ray Disc Player, DLNA, HDMI BP120',73.4,22,'Der BP120 ist mehr als einfach nur ein Blu-ray-Player. Mit seiner weitreichenden Formatunterst&uuml;tzung f&uuml;r DivX, MKV, FLV und viele mehr, die er auch problemlos von Ihrer externen Festplatte abspielt, ist er ein echtes Multimediatalent. Dank 1.080p Upscaler und erweiterter Farbtiefe durch Deep Color spielt der Player Ihre Filme garantiert in bester Bildqualit&auml;t ab.',10,48,49,'false',0.00),
('Sony BDP-S186 Blu-ray & DVD Player Silber',77.12,22,'HD-Bildqualit&auml;t Wiedergabe von DVDs Benutzerfreundliches Men&uuml;system Kompaktes und elegantes Design Zugang zu kostenlosem Online-Entertainment Vielseitige Dateikompatibilit&auml;t dank USB Geringer Stromverbrauch HDMI High Definition Audio-Codecs.',10,40,0,'false',0.00),
('Nintendo Wii U Premium Konsole 32GB Wi-Fi Nintendo Land schwarz (WIIU)',314.19,23,'Wii U ist eine brandneue Heim-Videospielkonsole von Nintendo, die f&uuml;r immer ver&auml;ndern wird, wie du mit dem Fernseher interagierst und wie deine Freunde und Familienmitglieder miteinander verbunden sind. Sie ist ein leistungsstarkes HD-Spielsystem mit einem au&szlig;ergew&ouml;hnlichen neuen Controller, der die Dynamik des gemeinsamen Spielens ganz neu definiert: Das ist das Wii U GamePad.',10,62,0,'true',6.00),
('Sony PlayStation 3 Konsole 500GB HDD WiFi & Bluetooth blau (PS3)',315.22,23,'Neues Design leichter und schlanker! Durch eine umfassende Neuentwicklung der internen Design-Architektur wurden die inneren Abmessungen und das Gewicht der neuen PS3 im Vergleich zum allerersten PS3-Modell mit einer 60-GB-Festplatte um mehr als die H&auml;lfte reduziert. Im Vergleich zur aktuellen PS3 konnten Reduzierungen von 20 % bzw. 25 % erzielt werden. Dank Einbau einer schiebbaren Festplattenabdeckung blieb das f&uuml;r die PS3 charakteristische glatte, abgerundete Design erhalten, das an den verschiedensten Aufstellorten eine gute Figur macht und Nutzer in die Lage versetzt, auf eine Vielzahl von Entertainment-Inhalten zuzugreifen.',10,40,49,'true',0.00),
('Microsoft XBox 360 Slim Konsole 4GB Wi-Fi Kinect Adventures/Kinect schwarz',265.07,23,'Das ideale Bundle f&uuml;r alle, die in die Welt der bewegungsgesteuerten Unterhaltung einsteigen wollen. Zum Lieferumfang der Xbox 360 mit 4 GB internem Speicherplatz, integriertem WLAN, HDMI-Anschluss und f&uuml;nf USB-Ports geh&ouml;ren auch der Kinect Sensor, die beiden bewegungsgesteuerten Spiele Kinect Adventures und Kinect Disneyland Adventures sowie eine Xbox LIVE Goldmitgliedschaft f&uuml;r einen Monat.',10,19,9,'false',0.00),
('Sony PlayStation Vita Konsole 512MB WiFi & Bluetooth schwarz (PSVITA)',278.2,23,'Melde dich f&uuml;r Inside PS Vita an um immer auf dem neuesten Stand rund um PS Vita zu sein. PlayStation haben au&szlig;erdem ein exklusives Design basierend auf Resistance: Burning Skies, LittleBigPlanet und Little Deviants zum Download f&uuml;r dich bereitstehen. Ein extrem leistungsf&auml;higer CPU/GPU erm&ouml;glicht in Kombination mit einer organischen Leuchtdiode (OLED) eine atemberaubend komplexe Grafik, die es so noch nicht f&uuml;r ein tragbares Entertainment-System gegeben hat. Dar&uuml;ber hinaus wurde PS Vita entsprechend dem Formfaktor Super Oval Design gestaltet, um den h&ouml;chstm&ouml;glichen ergonomischen Komfort zu erreichen. PS Vita ist mit einem einzigartigen R&uuml;ckseiten-Touchpad, einem Touchscreen auf der Vorderseite, Front- und R&uuml;ckseitenkameras sowie mit drei Bewegungssensoren, einem Kreisel, einem Beschleunigungssensor und einem elektronischen Kompass ausgestattet. Alle speziell f&uuml;r PS Vita entwickelten Titel werden in einem eigenen Bereich namens LiveArea Screens angeboten, in dem du Kontakte zu anderen kn&uuml;pfen kannst. Hier erh&auml;ltst du Zugriff auf aktuelle Spielinfos, die &uuml;ber das PlayStation Network bereitgestellt werden, sowie die M&ouml;glichkeit, ein st&auml;ndig aktualisiertes Logbuch der Aktivit&auml;t einzusehen, mit Freunden in Echtzeit zu chatten und vieles mehr. Als Teil der grundlegenden Funktionen wird SCE zudem ortsabh&auml;ngige Services f&uuml;r PS Vita &uuml;ber das PlayStation Network anbieten. Die neue Anwendung Umgebung, die speziell f&uuml;r diesen Service und das Netzwerk entwickelt wurde, ist auf dem System vorinstalliert.',10,40,4,'false',0.00),
('Nintendo 3DS XL Konsole 4GB Wi-Fi Pikachu Limited Edition gelb (3DSXL)',213.95,23,'Spiel, Fun und Unterhaltung in 3D! Mit 90% gr&ouml;&szlig;erem Bildschirm ist auf dem Nintendo 3DS XL noch mehr Platz zum Spielen und Staunen. Mit dabei nat&uuml;rlich die innovativen Funktionen: Mit StreetPass, sofern aktiviert, tauschen Spieler automatisch Items und mehr aus. Dank SpotPass lassen sich unterwegs neue Inhalte wie Filme oder Demos herunterladen. Durch die AR-Karten (Augmented Reality) erwachen die Spielcharaktere in der Realit&auml;t zum Leben. Diese kommen durch die Au&szlig;enkameras des Nintendo 3DS XL ins Bild. Mittels der doppelt so gro&szlig;en Speicherkarte kann er auch jede Menge Daten mit sich rumtragen. Au&szlig;erdem wurde die Akku-Leistung sp&uuml;rbar verbessert.',10,62,6,'false',0.00),
('46 Zoll (117cm) Samsung 8000er Serie UE46ES8000S 800Hz LED Analog/DVB-C/DVB-S (HD)/DVB-T',1394.57,24,'Der Samsung Slim LED TV bringt Ihnen die Zukunft des Home Entertainments nach Hause. Entdecken Sie zukunftsweisende Funktionen wie Sprach- und Gestensteuerung, Gesichtserkennung und viele weitere unterhaltsame Anwendungen wie Family Story und den Zugriff auf andere Ger&auml;te &uuml;ber AllShare Play. &Uuml;bertragen Sie Inhalte jetzt also ganz m&uuml;helos von Ihrem Computer oder mobilen Endger&auml;t auf Ihren Fernseher. Dank der erweiterten PVR-Funktion k&ouml;nnen Sie au&szlig;erdem Fernsehsendungen und Filme aufnehmen und speichern.',10,37,7,'false',0.00),
('40 Zoll (102cm) Philips 8000er Serie 40PFL8007K/12 800Hz LED Analog/DVB-C/DVB-C (HD)/DVB-S',1063.48,24,'Mitten im Geschehen! Genie&szlig;en Sie Full HD 3D und Smart TV mit Ambilight. Entdecken Sie eine Welt verschiedener Inhalte mit einem Philips 3D Smart LED-Fernseher 40PFL8007. Genie&szlig;en Sie die unbegrenzten M&ouml;glichkeiten durch Smart TV Premium, Skype&trade; auf Ihrem Fernseher mit der mitgelieferten Fernsehkamera sowie die einzigartige Fernbedienung mit integrierter PC-Tastatur und Mauszeiger.',10,61,7,'false',15.00),
('72 Zoll (183cm) LG Electronics Cinema 3D 72LM950V 1000Hz LED Analog/DVB-C/DVB-S/DVB-T',5309.12,24,'Kontrollieren Sie Ihr pers&ouml;nliches 3D-Programm mit der 3D-Tiefenkontrolle. Erleben Sie 3D-Inhalte mit einem leichten Tiefeneffekt oder st&uuml;rzen Sie sich direkt mitten ins Geschehen Sie haben die Wahl. Mit der individuell einstellbaren Tiefenkontrolle regulieren Sie die Intensit&auml;t des 3D-Effekts genau so, wie es f&uuml;r Sie am angenehmsten ist. Jetzt k&ouml;nnen Sie die dritte Dimension nicht nur sehen, sondern auch h&ouml;ren! Erleben Sie 3D mit allen Sinnen beim perfekten Zusammenspiel von Bild und Ton fast wie das echte Leben.',10,48,6,'false',0.00),
('32 Zoll (81cm) Blaupunkt B32P189TCSFDH-100 100Hz LED DVB-C/DVB-S/DVB-S (HD)/DVB-T',320.16,24,'100Hz Full HD LED-TV - H.264, Tripletuner f&uuml;r Analog und digital Fernsehempfang, DVB-T/C/S',10,50,44,'false',30.00),
('50 Zoll (127cm) Samsung Serie 6 UE50ES6710 400Hz LCD Analog/DVB-C/DVB-S (HD)/DVB-T',1114.73,24,'Entdecken Sie eine neue Welt sozialer und personalisierter Heimkinounterhaltung mit Samsungs weiterentwickeltem Smart Hub und drei gro&szlig;artigen neuen Features: Mit Family Story k&ouml;nnen Sie Fotos, Mitteilungen und besondere Ereignisse mit Ihren Liebsten teilen. Ihre Kinder sind mit der Kids-Funktion gut unterhalten und k&ouml;nnen dabei auch noch etwas lernen. &Uuml;ber die Fitness-Anwendung k&ouml;nnen Sie trainieren und Ihren Sportplan verwalten. Erleben Sie wundervolle Heimkinounterhaltung f&uuml;r die ganze Familie mit tollen Inhalten, Samsung Apps, Internetzugang, Skype und vielem mehr. Stecken Sie Ihren USB-Stick einfach in den USB-Anschluss des Fernsehers und genie&szlig;en Sie mit ConnectShare Movie sofort die darauf gespeicherten Filme, Fotos oder Musik. Erleben Sie eine Vielzahl an Multimedia-Inhalten in Ihrem Wohnzimmer.',10,37,0,'false',0.00),
('Skylanders Giants Starter Pack Wii U',64.54,25,'Skylanders l&auml;sst Kinder Spielzeug und Video&shy;spiele v&ouml;llig neu erleben und ver&auml;ndert die Weise, wie sie mit ihnen interagieren: Die Spielfiguren &quot;erinnern&quot; sich an alle dynami&shy;schen Erfahrungen ihres Abenteuers und k&ouml;nnen individuell ausgestattet werden. Spieler erwecken die Charaktere zum Leben, wenn sie sie auf das &quot;Portal of Power&quot; von Freunden stellen, um sich mit ihnen in spannenden Mehrspieler-Modi zu messen. Skylanders gibt Kindern die M&ouml;glich&shy;keit, jederzeit die Figur zu wechseln und so bei jedem Spielen eine andere Strategie anwenden zu k&ouml;nnen.',10,63,6448,'false',0.00),
('Sim City 5 Limited Edition (PC)',52.54,25,'Die erfolgreiche St&auml;dtebausimulation ist wieder da. Erschaffen Sie die Stadt Ihrer W&uuml;nsche und treffen Sie die richtigen Entscheidungen, um Ihrer Stadt ein Gesicht zu geben und die darin lebenden Sims zufriedenzustellen.',10,64,46,'true',0.00),
('FIFA 13 (PS3)',51.1,25,'Mit FIFA 13 kommt das umfangreichste Spiel in der Geschichte der Serie. Die Verbesserungen in Bereichen wie k&uuml;nstliche Intelligenz, Dribbling, Ballkontrolle und Kollisionen machen den Kampf um den Ball so spannend wie nie, bieten im Angriff ungeahnte Freiheiten, erm&ouml;glichen kreative Spielz&uuml;ge und fangen die Dramatik des echten Fu&szlig;balls ein. Die FIFA 13 First Touch Ball Control weist neue Wege bei der Ballbehandlung - die nahezu perfekte Kontrolle bei jedem Spieler in jeder Situation gibt es nicht mehr. So haben Verteidiger mehr M&ouml;glichkeiten, den Ball zu erobern. Schlechte P&auml;sse sind schwerer unter Kontrolle zu bringen, wovon Verteidiger profitieren k&ouml;nnen. Defensivdruck, Ballweg und Geschwindigkeit, das sind die Faktoren, die eine erfolgreiche Ballannahme bestimmen. Das Feature Attacking Intelligence versieht Spieler mit der bislang ausgereiftesten k&uuml;nstlichen Intelligenz. Die Akteure analysieren den Raum besser, setzen die Defensive st&auml;rker und intelligenter unter Druck und antizipieren Spielz&uuml;ge akkurater. Die Spieler ziehen bei Vorst&ouml;&szlig;en Verteidiger auf sich und &ouml;ffnen so Passwege f&uuml;r ihre Mitspieler. Ihre Laufwege gestalten sie dabei so, dass sie sich bietende R&auml;ume effizient nutzen. Baue dein Ultimate Team voller Fu&szlig;ballstars auf: Erhalte, kaufe, verkaufe und tausche Spieler und Objekte innerhalb der FIFA-Community. Erstelle und manage mehrere Mannschaften, um dann in w&ouml;chentlich aktualisierten Wettbewerben mit ihnen anzutreten. Mit der EA SPORTS Football Club App f&uuml;r iPhone verwaltest du auch unterwegs dein Team, durchforstest Live-Auktionen und bietest auf neue Spieler. Im Karrieremodus geht es jetzt noch internationaler zu. Spiele f&uuml;r deine Lieblingsnationalmannschaft oder trainiere sie, gleich ob in Freundschaftsspielen, Qualifikationen oder bedeutenden Turnieren. Als Trainer versuchst du einen Posten bei einer Nationalelf zu ergattern. Wichtige Entscheidungen sind zu treffen und der Druck ist enorm. Als Spieler musst du zun&auml;chst auf Vereinsebene &uuml;berzeugen, um in eine Nationalmannschaft berufen zu werden.',10,64,7,'true',0.00),
('Zumba Fitness Rush (Kinect (XBox 360)',42.29,25,'Zumba Fitness Rush (Zumba Fitness 2) &Uuml;ber drei Millionen Spieler haben das rasante und wirkungsvolle interaktive Workout des Zumba Fitness Videospiels f&uuml;r sich entdeckt. Nun tritt Zumba Fitness Rush in die Fu&szlig;stapfen des erfolgreichen Originals und verspricht allen Tanzfans noch mehr Spa&szlig;, Unterhaltung und hei&szlig;e Rhythmen. Tanzen Sie sich fit und sexy mit Zumba Fitness Rush!',10,19,0,'false',0.00),
('Super Mario Galaxy (WII)',45.45,25,'Super Mario Galaxy ist der Teil in der langen Reihe von Mario-Jump n Runs, der Ihren Blick auf Videospiele total ver&auml;ndern wird. Super Mario Galaxy ist das ultimative Mario-Erlebnis, von der faszinierenden Vielfalt der Galaxien und den Spezial-Outfits f&uuml;r Mario, bis zu der umwerfenden Steuerung, die durch die Wii-Fernbedienung m&ouml;glich wird. Im Weltraum ist nicht immer alles so, wie es scheint. Bei seinen Bem&uuml;hungen, Prinzessin Peach zu retten, jagt Mario von einer Galaxie in die n&auml;chste. Dabei kann er sich kaum vorstellen, welche neuen Herausforderungen ihn in den 40 einzigartigen Galaxien erwarten. Zum Gl&uuml;ck kann er auf Ihre Hilfe z&auml;hlen, und Sie haben die Wii-Fernbedienung. Mit der Wii-Fernbedienung k&ouml;nnen Sie Marios ber&uuml;hmte Spr&uuml;nge ausf&uuml;hren, w&auml;hrend er versucht, alle 120 Sterne zu entdecken und den Weg zur&uuml;ck ins Pilzk&ouml;nigreich zu finden. Ob Sie ein Mario-Meister sind oder zum ersten Mal eines seiner Abenteuer spielen, mit den Bewegungssensoren und den anderen F&auml;higkeiten des Controllers k&ouml;nnen Sie selber von Planet zu Planet springen. Marios neueste F&auml;higkeit - die Spirale - l&ouml;st man aus, indem man die Wii-Fernbedienung schnell sch&uuml;ttelt. Das ist die vielseitigste F&auml;higkeit im Spiel und sie kann Mario bei seinen vielen Entdeckungen sehr gute Dienste leisten. Indem man die Wii-Fernbedienung als Zeiger einsetzt, kann man auch noch Stern-Teile einsammeln, die man auf Gegner werfen kann, um sie zu bet&auml;uben. Eine weitere Neuerung, die durch die Verwendung der Wii-Fernbedienung als Zeiger m&ouml;glich ist, ist der Co-Stern-Modus. Im Co-Stern-Modus kann ein zweiter Spieler die Umgebung beeinflussen und so dem Spieler helfen, der Mario steuert, indem er Gegner festh&auml;lt und Stern-Teile abfeuert. Der Co-Stern kann Mario durch die Zusammenarbeit mit dem Spiel-Partner auch helfen, besonders hohe Spr&uuml;nge auszuf&uuml;hren. Zu all dem kommt noch die himmlische Grafik und die pr&auml;zise Kamerasteuerung. Die Kamera bewegt sich verl&auml;sslich mit Mario, so dass Sie immer die beste Sicht haben, um die Herausforderungen jeder Galaxie zu bew&auml;ltigen. Die grafische Tiefe, die durch die einzigartige Umgebung jeder Galaxie entsteht, sorgt f&uuml;r ein visuell beeindruckendes und atmosph&auml;risches Spielerlebnis. Dieses Mario-Spiel ist ein absolutes Muss, sowohl f&uuml;r alte Fans, als auch f&uuml;r Neuanf&auml;nger.',10,62,97,'false',1.00);


INSERT INTO OrdertArticleTab (ArtID, Number) VALUES 	

							(1,61),
							(2,52),
							(3,73);

INSERT INTO SpecTab (ArtID, Value1, Value2, Value3, Value4, Value5, Value6, Value7) VALUES 	

							(1,'345 mm','227 mm','272 mm','PC-Q08B','Wuerfel','ohne Netzteil','mITX, mDTX'),
							(2,'470 mm','215 mm','450 mm','TC-85S','Midi Tower','400 Watt','ATX, mATX, mITX'),
							(3,'414 mm','95 mm','310 mm','CA-011','Desktop','400 Watt','mATX, mITX'),
							(4,'450 mm','220 mm','440 mm','7802GDR','Midi Tower','420 Watt','ATX, mATX'),
							(5,'440 mm','218 mm','440 mm','Centurion 534 Plus','Midi Tower','ohne Netzteil','ATX'),
							(6,'Radeon HD 7750','PCIe 3.0 x16','Single GPU','1125MHz','55W','28nm','1024MB'),
							(7,'Radeon HD 5450','PCIe 2.1 x16','Single GPU','450MHz','19,1W','44nm','512MB'),
							(8,'Radeon HD 7990','PCIe 3.0 x16','Dual GPU','2x 1375MHz','< 300W','2x 28nm','6144MB'),
							(9,'GeForce GTX 680','PCIe 3.0 x16','Single GPU','1575MHz','195W','28nm','4096MB'),
							(10,'GeForce GTS 450','PCIe 2.0 x16','Single GPU','666MHz','75W','40nm','1024MB'),
							(11,'So.1155','Intel Q77','mATX','1x DVI, 1x VGA, 1x Displayport','DDR3','2x','1x 1000 MBit'),
							(12,'So.FM2','AMD A55','mATX','1x DVI, 1x VGA','DDR3','nicht vorhanden','1x 1000 MBit'),
							(13,'So.AM3+','AMD 990FX','ATX','nicht vorhanden','DDR3','7x','1x 1000 MBit'),
							(14,'So.BGA','Intel NM10','Mini-ITX','1x HDMI, 1x VGA','DDR2-800','nicht vorhanden','1x 1000 MBit'),
							(15,'So.1155','Intel Z77','mATX','1x HDMI, 1x Displayport','DDR3','4x','1x 1000 MBit'),
							(16,'Celeron','G460','Sandy Bridge','1x','1.80GHz','35W','Intel HD Graphics'),
							(17,'Core i5','3570k','Ivy Bridge','4x','3.40GHz','77W','Intel HD Graphics 4000'),
							(18,'Pentium','G850','Sandy Bridge','2x','2.90GHz','65W','Intel HD Graphics'),
							(19,'A8 Series','A8-5600K','Trinity','4x','3.60GHz','100W','AMD Radeon HD 7560D'),
							(20,'FX Series','FX-6300','Vishera','6x','3.50GHz','95W','nicht vorhanden'),
							(21,'System Power 7','300 Watt','ATX 2.31','80+ Bronze','1x ATX 20/24pol, 1x ATX12V 4+4pol, 1x 3.5 Zoll, 2x 5.25 Zoll, 4x SATA','Non-Modular','120mm Luefter'),
							(22,'RedWing R3','400 Watt','ATX 2.3','80+','1x ATX 20/24pol, 1x ATX12V 4pol, 1x 3.5 Zoll, 2x 5.25 Zoll, 4x SATA','Non-Modular','120mm Luefter'),
							(23,'CMX','550 Watt','ATX 2.3','80+ Bronze','1x ATX 20/24pol, 1x ATX12V 4+4pol, 1x ATX12V 8pol, 1x PCI Express 6+2pol, 2x PCI Express 6pol, 1x 3.5 Zoll, 5x 5.25 Zoll, 6x SATA','Modular','140mm Luefter'),
							(24,'Pure Power CM','430 Watt','ATX 2.3','80+ Bronze','1x ATX 20/24pol, 1x ATX12V 4+4pol, 1x PCI Express 6pol, 1x PCI Express 6+2pol, 1x 3.5 Zoll, 3x 5.25 Zoll, 4x SATA','Modular','120mm Luefter'),
							(25,'Strike-X','1100 Watt','ATX 2.3','80+ Gold','1x ATX 20/24pol, 1x ATX12V 4+4pol, 6x PCI Express 6+2pol, 1x PCI Express 8pol, 2x 3.5 Zoll, 8x 5.25 Zoll, 8x SATA','Modular','140mm Luefter');
